import type { ManoeuvreState } from '../state'
import type { VesselParameters } from '../vessel-parameters'

const KNOTS_PER_MPS = 1.9438444924406

export type ThrusterForces = {
  swayForce: number
  yawMoment: number
  effectiveness: number
}

export function bowThrusterEffectiveness(speedKnots: number, cutoffKnots: number) {
  const cutoff = Math.max(.1, cutoffKnots)
  const ratio = Math.max(0, speedKnots) / cutoff
  if (ratio >= 1) return 0
  if (ratio <= .4) return 1 - ratio
  if (ratio <= .8) return .6 - ((ratio - .4) / .4) * .45
  return .15 - ((ratio - .8) / .2) * .15
}

export function bowThrusterForces(state: ManoeuvreState, command: number, vessel: VesselParameters): ThrusterForces {
  const demand = Math.max(-1, Math.min(1, command))
  // Tunnel-thruster authority is primarily lost with longitudinal flow past the hull.
  // The lateral motion generated by the thruster itself must not switch the thruster off.
  const speedKnots = Math.abs(state.surge) * KNOTS_PER_MPS
  const effectiveness = bowThrusterEffectiveness(speedKnots, vessel.bowThrusterCutoffKnots)
  if (effectiveness <= 0 || Math.abs(demand) < 1e-12) return { swayForce: 0, yawMoment: 0, effectiveness }

  // Bridge +1 means STBD, while simulator +sway/+yaw is PORT.
  const swayForce = -demand * vessel.bowThrusterForce * effectiveness
  const yawMoment = swayForce * vessel.bowThrusterLeverArm
  return { swayForce, yawMoment, effectiveness }
}
