export const PORTS={HAM:{name:"Hamburg",lat:53.55,lon:9.99},RTM:{name:"Rotterdam",lat:51.92,lon:4.48},NYC:{name:"New York",lat:40.71,lon:-74.01},CPT:{name:"Cape Town",lat:-33.92,lon:18.42},DXB:{name:"Jebel Ali",lat:25.01,lon:55.06},SIN:{name:"Singapore",lat:1.29,lon:103.85},SHA:{name:"Shanghai",lat:31.23,lon:121.47},SSZ:{name:"Santos",lat:-23.96,lon:-46.33}};
export const CARGO=[{name:"Maschinenteile",rate:1.35,tons:[6000,12000]},{name:"Stahlprodukte",rate:1,tons:[9000,17000]},{name:"Kaffee",rate:1.65,tons:[5000,10000]},{name:"Chemikalien",rate:1.8,tons:[4000,9000]},{name:"Getreide",rate:.88,tons:[10000,18000]},{name:"Elektronik",rate:2.1,tons:[3000,7500]}];
const toRad=d=>d*Math.PI/180;
export function distanceNm(a,b){const R=6371,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lon-a.lon),la1=toRad(a.lat),la2=toRad(b.lat);const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return(2*R*Math.asin(Math.sqrt(h)))/1.852}
export function seeded(seed){let s=seed>>>0;return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296}}
export function makeContracts(portCode,day,count=3){const rand=seeded(day*101+portCode.charCodeAt(0)*17+portCode.charCodeAt(1));const dests=Object.keys(PORTS).filter(p=>p!==portCode);const ranked=dests.map(d=>({d,r:rand()})).sort((a,b)=>a.r-b.r).slice(0,count).map(x=>x.d);return ranked.map((dest,i)=>{const cargo=CARGO[Math.floor(rand()*CARGO.length)],tons=Math.round((cargo.tons[0]+rand()*(cargo.tons[1]-cargo.tons[0]))/100)*100,dist=distanceNm(PORTS[portCode],PORTS[dest]),days=Math.max(1,Math.ceil(dist/(18*24))),market=.85+rand()*.45,payout=Math.round((tons*cargo.rate*dist*.018*market)/1000)*1000;return{id:`${portCode}-${day}-${i}`,origin:portCode,destination:dest,cargo:cargo.name,tons,distanceNm:Math.round(dist),seaDays:days,payout,deadline:day+days+Math.max(2,Math.round(days*.25))}})}
export function initialState(){return{day:1,cash:420000,reputation:50,condition:84,fuel:820,shipValue:1150000,port:"HAM",voyage:null,selectedContractId:null,log:["Tag 1: Northstar Shipping nimmt den Betrieb in Hamburg auf."]}}
export function companyValue(s){return Math.round(s.cash+s.shipValue*(s.condition/100))}
export function fuelCostForDay(distanceDayNm,fuelPrice=690){const burn=52*Math.min(1,distanceDayNm/(18*24));return{burn,cost:Math.round(burn*fuelPrice)}}
export function startVoyage(state,contract){if(!contract)throw new Error("contract required");if(contract.tons>18000)throw new Error("capacity exceeded");return{...state,selectedContractId:null,voyage:{contract,elapsed:0,total:contract.seaDays,eventTriggered:false,origin:contract.origin,destination:contract.destination},log:[`Tag ${state.day}: ${contract.cargo} (${contract.tons.toLocaleString("de-DE")} t) nach ${PORTS[contract.destination].name} übernommen.`,...state.log]}}
export function advanceDay(state){if(!state.voyage)return state;let voyage=state.voyage,total=voyage.total,event=null;const rand=seeded(state.day*313+voyage.contract.id.length*71),distancePerDay=voyage.contract.distanceNm/total,fuel=fuelCostForDay(distancePerDay);let conditionLoss=.35,extraCost=0,repDelta=0;if(!voyage.eventTriggered&&voyage.elapsed>=1&&rand()<.27){const r=rand();if(r<.45){event={title:"Schwere See",text:"Die Geschwindigkeit muss reduziert werden. Die Reise verlängert sich um einen Tag."};total+=1;conditionLoss+=.5}else if(r<.78){event={title:"Pumpenstörung",text:"Eine Hilfspumpe wird repariert. Kosten: 18.000 €."};extraCost=18000;conditionLoss+=1.4}else{event={title:"Günstige Strömung",text:"Die Passage verläuft effizienter als erwartet. Treibstoffersparnis: 8.000 €."};extraCost=-8000;repDelta=1}voyage={...voyage,eventTriggered:true}}const newDay=state.day+1,elapsed=voyage.elapsed+1,fuelLeft=Math.max(0,state.fuel-fuel.burn),cash=state.cash-fuel.cost-extraCost,condition=Math.max(25,state.condition-conditionLoss);if(fuelLeft<=0)return{...state,day:newDay,cash,fuel:fuelLeft,condition,voyage:null,reputation:Math.max(0,state.reputation-8),lastEvent:{title:"Treibstoff erschöpft",text:"Die Reise wurde abgebrochen. Reputation −8."},log:[`Tag ${newDay}: Reise abgebrochen — Treibstoff erschöpft.`,...state.log]};if(elapsed>=total){const late=newDay>voyage.contract.deadline,payout=late?Math.round(voyage.contract.payout*.72):voyage.contract.payout,rep=late?-2:3;return{...state,day:newDay,cash:cash+payout,fuel:fuelLeft,condition,port:voyage.destination,voyage:null,reputation:Math.max(0,state.reputation+repDelta+rep),lastEvent:event,log:[`Tag ${newDay}: ${PORTS[voyage.destination].name} erreicht — ${payout.toLocaleString("de-DE")} € Frachterlös${late?" (verspätet)":""}.`,...state.log]}}return{...state,day:newDay,cash,fuel:fuelLeft,condition,reputation:state.reputation+repDelta,voyage:{...voyage,elapsed,total},lastEvent:event,log:[...(event?[`Tag ${newDay}: ${event.title}.`]:[]),`Tag ${newDay}: Auf See — ${Math.round((elapsed/total)*100)} % der Passage abgeschlossen.`,...state.log]}}
export function serviceShip(state){const fuelNeeded=900-state.fuel,fuelCost=Math.max(0,Math.round(fuelNeeded*690)),repairPoints=100-state.condition,repairCost=Math.round(repairPoints*3200),total=fuelCost+repairCost;if(state.cash<total)return state;return{...state,cash:state.cash-total,fuel:900,condition:100,log:[`Tag ${state.day}: Schiff gewartet und gebunkert — ${total.toLocaleString("de-DE")} €.`,...state.log]}}
