import{PORTS,makeContracts,initialState,companyValue,startVoyage,advanceDay,serviceShip}from"./engine.mjs";
const $=id=>document.getElementById(id),fmt=n=>`${Math.round(n).toLocaleString("de-DE")} €`,pct=n=>`${Math.round(n)} %`;
let state=load(),contracts=makeContracts(state.port,state.day);
function load(){try{const v=JSON.parse(localStorage.getItem("ocean-trader-prototype"));return v&&v.day?v:initialState()}catch{return initialState()}}
function save(){localStorage.setItem("ocean-trader-prototype",JSON.stringify(state))}
function xy(p){return{x:((p.lon+180)/360)*100,y:((90-p.lat)/180)*100}}
function renderMap(){const map=$("map");map.innerHTML="";Object.entries(PORTS).forEach(([code,p])=>{const{x,y}=xy(p),el=document.createElement("div");el.className="port"+(code===state.port?" current":"")+(state.voyage?.destination===code?" destination":"");el.style.left=`${x}%`;el.style.top=`${y}%`;el.innerHTML=`<span>${p.name}</span>`;map.appendChild(el)});if(state.voyage){const a=xy(PORTS[state.voyage.origin]),b=xy(PORTS[state.voyage.destination]),dx=b.x-a.x,dy=b.y-a.y,line=document.createElement("div");line.className="route-line";line.style.left=`${a.x}%`;line.style.top=`${a.y}%`;line.style.width=`${Math.sqrt(dx*dx+dy*dy)}%`;line.style.transform=`rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)`;map.appendChild(line);const t=Math.min(1,state.voyage.elapsed/state.voyage.total),ship=document.createElement("div");ship.className="ship-dot";ship.style.left=`${a.x+(b.x-a.x)*t}%`;ship.style.top=`${a.y+(b.y-a.y)*t}%`;map.appendChild(ship)}}
function renderContracts(){const box=$("contracts");if(state.voyage){box.innerHTML='<div class="small">Auf See — neue Aufträge werden im Zielhafen angeboten.</div>';return}contracts=makeContracts(state.port,state.day);box.innerHTML="";contracts.forEach(c=>{const label=document.createElement("label");label.className="contract"+(state.selectedContractId===c.id?" selected":"");label.innerHTML=`<div><input type="radio" name="contract" ${state.selectedContractId===c.id?"checked":""}> ${c.cargo}</div><strong>${PORTS[c.destination].name}</strong><div class="contract-meta"><span>${c.tons.toLocaleString("de-DE")} t · ${c.distanceNm.toLocaleString("de-DE")} sm</span><span>${c.seaDays} Seetage · Frist Tag ${c.deadline}</span><span>${fmt(c.payout)}</span></div>`;label.onclick=()=>{state.selectedContractId=c.id;render()};box.appendChild(label)})}
function renderAction(){const btn=$("primaryBtn"),sec=$("secondaryBtn");$("eventBox").hidden=!state.lastEvent;if(state.lastEvent){$("eventTitle").textContent=state.lastEvent.title;$("eventText").textContent=state.lastEvent.text}if(state.voyage){$("actionTitle").textContent="Passage durchführen";$("actionText").textContent=`${PORTS[state.voyage.origin].name} → ${PORTS[state.voyage.destination].name}. Jeder Klick simuliert einen Seetag inklusive Verbrauch, Verschleiß und möglicher Ereignisse.`;btn.textContent="Nächsten Seetag simulieren";btn.disabled=false;btn.onclick=()=>{state={...advanceDay(state),lastEvent:null};save();render()};sec.hidden=true}else{$("actionTitle").textContent="Auftrag auswählen";$("actionText").textContent="Wähle einen Frachtauftrag. Nach der Übernahme beginnt die Passage sofort.";btn.textContent="Auftrag übernehmen";btn.disabled=!state.selectedContractId;btn.onclick=()=>{const c=contracts.find(x=>x.id===state.selectedContractId);state={...startVoyage(state,c),lastEvent:null};save();render()};sec.hidden=false;sec.textContent="Warten & Schiff warten/bunkern";sec.onclick=()=>{state={...serviceShip(state),day:state.day+1,selectedContractId:null,lastEvent:null};save();render()}}}
function render(){$("dayValue").textContent=state.day;$("positionValue").textContent=state.voyage?"Auf See":PORTS[state.port].name;$("marketLocation").textContent=state.voyage?"Markt geschlossen":`Markt: ${PORTS[state.port].name}`;$("cashValue").textContent=fmt(state.cash);$("repValue").textContent=`${state.reputation}/100`;$("valueValue").textContent=fmt(companyValue(state));$("conditionValue").textContent=pct(state.condition);$("fuelValue").textContent=`${Math.round(state.fuel)} t`;if(state.voyage){const p=Math.min(100,state.voyage.elapsed/state.voyage.total*100);$("etaValue").textContent=`${Math.max(0,state.voyage.total-state.voyage.elapsed)} Tage`;$("progressValue").textContent=pct(p);$("routeTitle").textContent=`${PORTS[state.voyage.origin].name} → ${PORTS[state.voyage.destination].name}`;$("statusPill").textContent="AUF SEE"}else{$("etaValue").textContent="—";$("progressValue").textContent="0%";$("routeTitle").textContent=PORTS[state.port].name;$("statusPill").textContent="IM HAFEN"}renderMap();renderContracts();renderAction();$("log").innerHTML=state.log.slice(0,14).map(x=>`<div class="log-entry">${x}</div>`).join("")}
$("resetBtn").onclick=()=>{state=initialState();save();render()};render();
