import assert from "node:assert/strict";
import {PORTS,distanceNm,makeContracts,initialState,startVoyage,advanceDay,companyValue} from "./engine.mjs";
const hamNyc=distanceNm(PORTS.HAM,PORTS.NYC);
assert.ok(hamNyc>3000&&hamNyc<4000,`HAM-NYC distance unexpected: ${hamNyc}`);
const contracts=makeContracts("HAM",1);
assert.equal(contracts.length,3);
assert.ok(contracts.every(c=>c.origin==="HAM"));
assert.ok(contracts.every(c=>c.tons<=18000));
assert.ok(contracts.every(c=>c.payout>0));
let s=initialState();
const startingValue=companyValue(s);
s=startVoyage(s,contracts[0]);
assert.ok(s.voyage);
let guard=30;
while(s.voyage&&guard-->0)s=advanceDay(s);
assert.ok(!s.voyage,"voyage should terminate");
assert.ok(s.day>1);
assert.ok(Number.isFinite(companyValue(s)));
assert.ok(startingValue>0);
console.log("engine tests: PASS");
