import{HANDYSIZE_RUNTIME_BITMAP}from'./bitmap/handysize-runtime';
import{FEEDER_BITMAP}from'./bitmap/feeder';

type ShipKind='coaster'|'handysize'|'feeder'|'panamax';
const DPR=2;
const WORLD_CHART_BITMAP='/art/bitmap/world-chart.webp';
const SHIP_ART:Record<ShipKind,string>={coaster:'/art/bitmap/coaster.webp',handysize:HANDYSIZE_RUNTIME_BITMAP,feeder:FEEDER_BITMAP,panamax:'/art/bitmap/panamax.webp'};
const SHIP_FALLBACK='/art/bitmap/coaster.webp';

function rng(seed:number){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}}
function drawHarbour(canvas:HTMLCanvasElement){const W=1200,H=720;canvas.width=W*DPR;canvas.height=H*DPR;const c=canvas.getContext('2d');if(!c)return;c.scale(DPR,DPR);const g=c.createLinearGradient(0,0,W,H);g.addColorStop(0,'#0b3c4c');g.addColorStop(.6,'#082b39');g.addColorStop(1,'#061d28');c.fillStyle=g;c.fillRect(0,0,W,H);const waterRng=rng(918);for(let i=0;i<1700;i++){c.fillStyle=`rgba(124,196,211,${.012+waterRng()*.045})`;const y=waterRng()*H;c.fillRect(waterRng()*W,y,12+waterRng()*42,.7)}const quay=(x:number,y:number,w:number,h:number)=>{c.fillStyle='#242d2f';c.fillRect(x,y,w,h);c.strokeStyle='#8c774a';c.lineWidth=2;c.strokeRect(x,y,w,h)};quay(820,105,340,42);quay(820,247,340,42);quay(1120,105,40,184);quay(330,450,260,34);quay(330,450,34,170);for(let x=835;x<1110;x+=48){c.fillStyle=x%96<48?'#a9542f':'#38586a';c.fillRect(x,76,36,20);c.fillStyle='#c38b42';c.fillRect(x+5,54,31,17)}for(let i=0;i<4;i++){const x=842+i*76;c.strokeStyle='#647d87';c.lineWidth=4;c.beginPath();c.moveTo(x,104);c.lineTo(x+20,55);c.lineTo(x+57,103);c.stroke();c.strokeStyle='#d3a64e';c.lineWidth=1.5;c.beginPath();c.moveTo(x+20,55);c.lineTo(x+55,55);c.stroke()}c.fillStyle='rgba(225,178,82,.16)';c.fillRect(930,180,170,54);c.strokeStyle='rgba(225,178,82,.42)';c.setLineDash([10,10]);c.strokeRect(930,180,170,54);c.setLineDash([]);const shade=c.createRadialGradient(780,320,80,780,320,720);shade.addColorStop(.55,'rgba(0,0,0,0)');shade.addColorStop(1,'rgba(0,0,0,.38)');c.fillStyle=shade;c.fillRect(0,0,W,H)}
function drawCargo(canvas:HTMLCanvasElement,kind:string){const S=56;canvas.width=S*DPR;canvas.height=S*DPR;const c=canvas.getContext('2d');if(!c)return;c.scale(DPR,DPR);c.fillStyle='#081b24';c.fillRect(0,0,S,S);c.strokeStyle='#9f824b';c.strokeRect(1,1,S-2,S-2);c.strokeStyle='#e2b75f';c.fillStyle='#d9a74c';c.lineWidth=2;if(kind==='chemical'){c.beginPath();c.moveTo(22,10);c.lineTo(34,10);c.moveTo(25,10);c.lineTo(25,22);c.lineTo(13,43);c.quadraticCurveTo(28,51,43,43);c.lineTo(31,22);c.lineTo(31,10);c.stroke()}else if(kind==='reefer'){c.beginPath();for(let a=0;a<6;a++){const t=a*Math.PI/3;c.moveTo(28,28);c.lineTo(28+Math.cos(t)*18,28+Math.sin(t)*18)}c.stroke()}else if(kind==='bulk'){c.beginPath();c.moveTo(10,42);c.quadraticCurveTo(28,8,46,42);c.closePath();c.fill()}else{c.fillRect(11,15,34,27);c.strokeStyle='#102631';for(let x=16;x<45;x+=8){c.beginPath();c.moveTo(x,16);c.lineTo(x,41);c.stroke()}}}
function cargoKind(text:string){const s=text.toLowerCase();if(s.includes('chem'))return'chemical';if(s.includes('reefer')||s.includes('kühl'))return'reefer';if(s.includes('bulk')||s.includes('erz')||s.includes('kohle')||s.includes('getreide'))return'bulk';return'general'}
function shipKind(text:string):ShipKind{const s=text.toLowerCase();if(s.includes('panamax')||s.includes('atlas crown'))return'panamax';if(s.includes('feeder')||s.includes('pacific link'))return'feeder';if(s.includes('coaster')||s.includes('baltic star')||s.includes('nordwind'))return'coaster';return'handysize'}
function configureErrorFallback(img:HTMLImageElement,cls:string){if(img.dataset.fallbackConfigured)return;img.dataset.fallbackConfigured='1';img.addEventListener('error',()=>{if(cls.includes('world-art')){img.classList.add('asset-missing');img.removeAttribute('src');return}if(img.getAttribute('src')!==SHIP_FALLBACK){img.setAttribute('src',SHIP_FALLBACK);return}img.classList.add('asset-missing');img.removeAttribute('src')})}
function addImage(host:Element,cls:string,src:string,where:'prepend'|'append'='prepend'){let img=host.querySelector<HTMLImageElement>(`.${cls}`);if(!img){img=document.createElement('img');img.className=cls;img.alt='';img.setAttribute('aria-hidden','true');img.decoding='async';where==='prepend'?host.prepend(img):host.append(img)}configureErrorFallback(img,cls);if(img.getAttribute('src')!==src)img.setAttribute('src',src)}
function addHeroImage(card:HTMLElement,src:string){const existing=Array.from(card.querySelectorAll<HTMLImageElement>('.vessel-hero-art'));let img=existing.shift();existing.forEach(n=>n.remove());if(!img){img=document.createElement('img');img.className='vessel-hero-art';img.alt='';img.setAttribute('aria-hidden','true');img.decoding='async';const head=card.querySelector('.detail-head');head?head.insertAdjacentElement('afterend',img):card.prepend(img)}configureErrorFallback(img,'vessel-hero-art');if(img.getAttribute('src')!==src)img.setAttribute('src',src)}
function fitMapScale(scale:HTMLElement){const scroll=scale.parentElement;if(!scroll)return;const current=scale.style.width;if(current!==scale.dataset.hybridApplied){const raw=parseFloat(current||'640');scale.dataset.hybridZoom=String(Math.max(1,Math.min(2.4,raw/640)))}const zoom=parseFloat(scale.dataset.hybridZoom||'1');const applied=`${Math.round(scroll.clientWidth*zoom)}px`;if(current===applied)return;scale.dataset.hybridApplied=applied;scale.style.width=applied}
function removeLegacyWorldArt(host:Element){host.querySelectorAll('.world-art-canvas,.dc-world-art-canvas').forEach(n=>n.remove())}
function decorate(){document.querySelectorAll<HTMLElement>('.brand-mark').forEach(mark=>addImage(mark,'brand-art','/art/ocean-trader-mark.svg','append'));document.querySelectorAll<HTMLElement>('.dc-wheel').forEach(mark=>addImage(mark,'dc-brand-art','/art/ocean-trader-mark.svg','append'));document.querySelectorAll<HTMLElement>('.map-scale').forEach(scale=>{fitMapScale(scale);removeLegacyWorldArt(scale);addImage(scale,'world-art-bitmap',WORLD_CHART_BITMAP,'prepend')});document.querySelectorAll<HTMLElement>('.dc-chart').forEach(chart=>{removeLegacyWorldArt(chart);addImage(chart,'dc-world-art-bitmap',WORLD_CHART_BITMAP,'prepend')});document.querySelectorAll<HTMLElement>('.harbour-stage').forEach(stage=>{if(!stage.querySelector('.harbour-art-canvas')){const canvas=document.createElement('canvas');canvas.className='harbour-art-canvas';drawHarbour(canvas);stage.prepend(canvas)}});document.querySelectorAll<HTMLElement>('.fleet-row,.ship-offer,.dc-fleet-list button').forEach(row=>{const kind=shipKind(row.textContent||'');addImage(row,'fleet-vessel-art',SHIP_ART[kind])});document.querySelectorAll<HTMLElement>('.vessel-dossier,.offer-detail').forEach(card=>{const kind=shipKind(card.querySelector('.label')?.textContent||card.textContent||'');addHeroImage(card,SHIP_ART[kind])});document.querySelectorAll('.port-operations-art').forEach(n=>n.remove());document.querySelectorAll<HTMLElement>('.contract-card').forEach(card=>{if(!card.querySelector('.cargo-art')){const canvas=document.createElement('canvas');canvas.className='cargo-art';drawCargo(canvas,cargoKind(card.querySelector('h3')?.textContent||''));card.append(canvas)}card.classList.add('hybrid-contract')})}
let queued=false;const schedule=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;decorate()})};new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['style']});window.addEventListener('resize',schedule);document.addEventListener('DOMContentLoaded',schedule);schedule();
