import React,{useMemo,useState,useEffect}from'react';
import{createRoot}from'react-dom/client';
import{acceptContract,advanceAllVoyagesDay,attentionCount,availableContractsForVessel,bunkerPrice,companyValue,contractForVoyage,createInitialState,currentEra,currency,FINANCING_OFFERS,nextInstallment,ports,repayLoanInstallment,takeLoan,totalDebt,vesselMarketValue,voyageForVessel,type GameState,type PortId,type Vessel}from'./domain';
import{etaDays,mapPorts,portById,project,vesselMapPosition,voyageProgress}from'./map';
import{loadState,saveState}from'./storage';
import'./desktop.css';

type Focus={kind:'vessel';id:string}|{kind:'port';id:PortId};

function DesktopCommandCenter(){
 const[state,setState]=useState<GameState>(()=>loadState(localStorage)??createInitialState());
 const[selected,setSelected]=useState(state.vessels[0]?.id??'');
 const[focus,setFocus]=useState<Focus>({kind:'vessel',id:state.vessels[0]?.id??''});
 useEffect(()=>saveState(localStorage,state),[state]);
 const era=currentEra(state),vessel=state.vessels.find(v=>v.id===selected)??state.vessels[0];
 const apply=(fn:(s:GameState)=>GameState)=>{try{setState(fn)}catch(e){alert(e instanceof Error?e.message:'Aktion fehlgeschlagen.')}};
 const start=(v:string,c:string)=>{apply(s=>acceptContract(s,v,c));setSelected(v);setFocus({kind:'vessel',id:v})};
 return <div className="dc-shell">
  <header className="dc-header"><div className="dc-brand"><span className="dc-wheel">✦</span><div><small>NORTHSTAR SHIPPING · GLOBAL OPERATIONS</small><h1>Ocean Trader</h1></div></div><div className="dc-head-stats"><Stat label="Epoche" value={era.name}/><Stat label="Datum" value={state.campaignDate}/><Stat label="Liquidität" value={currency(state.cash)}/><Stat label="Attention" value={`${attentionCount(state)}`}/></div></header>
  <main className="dc-grid">
   <Panel className="dc-map" title="Global Fleet Command" kicker="WORLD OPERATIONS"><WorldMap state={state} focus={focus} onFocus={setFocus}/></Panel>
   <Panel className="dc-hq" title="Reedereibüro" kicker="HEADQUARTERS"><Headquarters state={state}/></Panel>
   <Panel className="dc-market" title="Frachtbörsen-Terminal" kicker="FREIGHT EXCHANGE"><FreightTerminal state={state} onStart={start}/></Panel>
   <Panel className="dc-fleet" title="Werft & Flottenübersicht" kicker="FLEET REGISTER"><FleetPanel state={state} selected={selected} onSelect={id=>{setSelected(id);setFocus({kind:'vessel',id})}}/></Panel>
   <Panel className="dc-bridge" title="Ship Bridge HUD" kicker="LIVE VESSEL"><BridgeHUD state={state} vessel={vessel} onAdvance={()=>apply(advanceAllVoyagesDay)}/></Panel>
   <Panel className="dc-events" title="Ereignisse & Warnungen" kicker="OPERATIONS FEED"><Events state={state}/></Panel>
   <Panel className="dc-finance" title="Finance & Contracts" kicker="CAPITAL"><Finance state={state} onFinance={id=>apply(s=>takeLoan(s,id))} onRepay={id=>apply(s=>repayLoanInstallment(s,id))}/></Panel>
  </main>
  <footer className="dc-footer"><span>Ocean Trader · Local-first campaign</span><span><a href="/impressum.html">Impressum</a> · <a href="/datenschutz.html">Datenschutz</a></span></footer>
 </div>
}
function Panel({title,kicker,className='',children}:{title:string;kicker:string;className?:string;children:React.ReactNode}){return <section className={`dc-panel ${className}`}><header><div><small>{kicker}</small><h2>{title}</h2></div><i/></header><div className="dc-panel-body">{children}</div></section>}
function Stat({label,value}:{label:string;value:string}){return <div className="dc-stat"><span>{label}</span><strong>{value}</strong></div>}
function WorldMap({state,focus,onFocus}:{state:GameState;focus:Focus;onFocus:(f:Focus)=>void}){return <div className="dc-chart"><svg viewBox="0 0 1000 520"><defs><radialGradient id="oceanGlow"><stop offset="0" stopColor="#17495d"/><stop offset="1" stopColor="#071b27"/></radialGradient></defs><rect width="1000" height="520" fill="url(#oceanGlow)"/>{[100,200,300,400].map(y=><line key={y} x1="0" y1={y} x2="1000" y2={y} className="dc-gridline"/>)}{[125,250,375,500,625,750,875].map(x=><line key={x} x1={x} y1="0" x2={x} y2="520" className="dc-gridline"/>)}{state.voyages.map(v=>{const c=contractForVoyage(state,v);if(!c)return null;const a=project(portById(c.origin).lat,portById(c.origin).lon),b=project(portById(c.destination).lat,portById(c.destination).lon);return <line key={v.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} className="dc-route"/>})}{mapPorts.map(p=>{const q=project(p.lat,p.lon),active=focus.kind==='port'&&focus.id===p.id;return <g key={p.id} className={active?'dc-port active':'dc-port'} onClick={()=>onFocus({kind:'port',id:p.id})}><circle cx={q.x} cy={q.y} r={active?7:4}/>{active&&<text x={q.x+10} y={q.y-8}>{p.name}</text>}</g>})}{state.vessels.map(v=>{const q=vesselMapPosition(state,v),active=focus.kind==='vessel'&&focus.id===v.id;return <g key={v.id} className={active?'dc-vessel active':'dc-vessel'} onClick={()=>onFocus({kind:'vessel',id:v.id})}><circle cx={q.x} cy={q.y} r={active?11:8}/><path d={`M ${q.x-7} ${q.y} L ${q.x+9} ${q.y-5} L ${q.x+5} ${q.y+5} Z`}/></g>})}</svg><div className="dc-map-legend"><span><i className="gold"/>Hafen</span><span><i className="cyan"/>Schiff</span><span>{state.voyages.length} aktive Routen</span></div></div>}
function Headquarters({state}:{state:GameState}){const value=companyValue(state),debt=totalDebt(state);return <div className="dc-hq-grid"><div className="dc-bank"><span>Bank Balance</span><strong>{currency(state.cash)}</strong><div className="spark"><i/><i/><i/><i/><i/><i/></div></div><div className="dc-paper"><span>Company Value</span><b>{currency(value)}</b><small>Debt {currency(debt)}</small></div><div className="dc-paper"><span>Reputation</span><b>{state.reputation}/100</b><small>{state.completedContracts.length} completed contracts</small></div><div className="dc-messages"><span>Message List</span>{state.transactionLog.slice(0,4).map((l,i)=><p key={i}>▸ {l}</p>)}</div></div>}
function FreightTerminal({state,onStart}:{state:GameState;onStart:(v:string,c:string)=>void}){const rows=state.vessels.flatMap(v=>availableContractsForVessel(state,v.id).slice(0,3).map(c=>({v,c}))).slice(0,6);return <div className="dc-ticker">{rows.map(({v,c})=><button key={`${v.id}-${c.id}`} onClick={()=>onStart(v.id,c.id)}><span className="cargo-icon">{cargoIcon(c.cargo)}</span><span className="ticker-route"><b>{ports[c.origin]} → {ports[c.destination]}</b><small>{c.cargo} · {v.name}</small></span><span className="ticker-price"><b>{currency(c.payout)}</b><small>{c.days} d · {c.tonnes.toLocaleString('de-DE')} t</small></span></button>)}</div>}
function cargoIcon(c:string){const x=c.toLowerCase();if(x.includes('stahl')||x.includes('maschine'))return'⚙';if(x.includes('chem'))return'◉';if(x.includes('papier'))return'▤';if(x.includes('konsum'))return'▣';return'▦'}
function FleetPanel({state,selected,onSelect}:{state:GameState;selected:string;onSelect:(id:string)=>void}){return <div className="dc-fleet-list">{state.vessels.map(v=>{const voyage=voyageForVessel(state,v.id),c=voyage?contractForVoyage(state,voyage):null;return <button key={v.id} className={selected===v.id?'active':''} onClick={()=>onSelect(v.id)}><ShipSilhouette/><span><b>{v.name}</b><small>{v.className} · {v.capacityTonnes.toLocaleString('de-DE')} t</small><em>{c?`${ports[c.origin]} → ${ports[c.destination]}`:v.currentPort?ports[v.currentPort]:'At sea'}</em></span><span className="dc-condition"><b>{v.condition.toFixed(0)}%</b><progress max="100" value={v.condition}/><small>{currency(vesselMarketValue(v,state.campaignDate))}</small></span></button>})}</div>}
function ShipSilhouette(){return <svg className="ship-sil" viewBox="0 0 120 45"><path d="M5 28 L18 38 L95 38 L115 27 L102 27 L96 17 L70 17 L65 8 L48 8 L44 17 L25 17 L21 28 Z"/><rect x="53" y="11" width="9" height="5"/><rect x="73" y="20" width="18" height="6"/></svg>}
function BridgeHUD({state,vessel,onAdvance}:{state:GameState;vessel:Vessel|undefined;onAdvance:()=>void}){if(!vessel)return null;const voyage=voyageForVessel(state,vessel.id),c=voyage?contractForVoyage(state,voyage):null,progress=voyage?voyageProgress(voyage):0;return <div className="dc-bridge-hud"><div className="gauges"><Gauge label="ENGINE" value={Math.round(vessel.fuelTonnes/vessel.fuelCapacityTonnes*100)} unit="FUEL"/><Gauge label="SPEED" value={voyage?vessel.speedKnots:0} unit="KN" max={25}/><Gauge label="HULL" value={Math.round(vessel.condition)} unit="%"/></div><div className="radar"><i/><span>{c?`${ports[c.origin]} → ${ports[c.destination]}`:'PORT OPS'}</span></div><div className="bridge-route"><b>{vessel.name}</b><span>{c?`ETA ${etaDays(voyage!)} Tage · ${Math.round(progress*100)}%`:`${vessel.currentPort?ports[vessel.currentPort]:'Auf See'} · bereit`}</span></div><button className="dc-action" disabled={!state.voyages.some(x=>!x.arrivalPending)} onClick={onAdvance}>SIMULATE +1 DAY</button></div>}
function Gauge({label,value,unit,max=100}:{label:string;value:number;unit:string;max?:number}){const pct=Math.max(0,Math.min(1,value/max)),deg=-120+pct*240;return <div className="gauge"><span>{label}</span><div className="dial"><i style={{transform:`rotate(${deg}deg)`}}/><b>{value}</b></div><small>{unit}</small></div>}
function Events({state}:{state:GameState}){const warnings:React.ReactNode[]=[];state.vessels.forEach(v=>{const voyage=voyageForVessel(state,v.id);if(voyage?.arrivalPending)warnings.push(<div className="event critical" key={`${v.id}-dock`}><b>⚠ DOCKING REQUIRED</b><span>{v.name} wartet auf Hafenmanöver.</span></div>);if(v.condition<75)warnings.push(<div className="event warning" key={`${v.id}-hull`}><b>△ MAINTENANCE</b><span>{v.name}: Zustand {v.condition.toFixed(0)}%</span></div>);if(v.fuelTonnes/v.fuelCapacityTonnes<.25)warnings.push(<div className="event warning" key={`${v.id}-fuel`}><b>◉ LOW BUNKER</b><span>{v.name}: Fuel Reserve niedrig.</span></div>)});if(!warnings.length)warnings.push(<div className="event ok" key="ok"><b>✓ OPERATIONS NORMAL</b><span>Keine kritischen Warnungen.</span></div>);return <div className="dc-events-list">{warnings.slice(0,4)}<div className="event illustration"><div className="event-sea">≈ ≈ <span>▰</span> ≈ ≈</div><b>LIVE OPERATIONS</b><span>{state.voyages.length} voyages · {state.vessels.length} vessels</span></div></div>}
function Finance({state,onFinance,onRepay}:{state:GameState;onFinance:(id:string)=>void;onRepay:(id:string)=>void}){return <div className="dc-finance-body"><div className="dc-debt"><span>Outstanding debt</span><strong>{currency(totalDebt(state))}</strong></div>{state.loans.slice(0,2).map(l=><div className="dc-loan" key={l.id}><span><b>{l.name}</b><small>{l.paymentsMade}/{l.installments} paid</small></span><button disabled={state.cash<nextInstallment(l)} onClick={()=>onRepay(l.id)}>{currency(nextInstallment(l))}</button></div>)}{state.loans.length===0&&FINANCING_OFFERS.slice(0,2).map(o=><div className="dc-loan" key={o.id}><span><b>{o.name}</b><small>{o.description}</small></span><button onClick={()=>onFinance(o.id)}>+ {currency(o.principal)}</button></div>)}</div>}

const mount=document.getElementById('desktop-root');if(mount&&window.matchMedia('(min-width:1100px)').matches){document.documentElement.classList.add('desktop-command');createRoot(mount).render(<React.StrictMode><DesktopCommandCenter/></React.StrictMode>)}
