import{describe,expect,it}from'vitest';
import{acceptContract,advanceAllVoyagesDay,advanceVoyageDay,buyShip,companyValue,completeHarbourArrival,createInitialState,refuelVessel,repairVessel,repayLoanInstallment,sellVessel,takeLoan,totalDebt,vesselMarketValue,voyageForVessel}from'./domain';

describe('fleet commerce and finance domain',()=>{
 it('runs voyages independently and settles harbour arrival exactly once',()=>{let s=createInitialState();s=acceptContract(s,'ot-vessel-001','C-HAM-RTM-001');s=acceptContract(s,'ot-vessel-002','C-RTM-NYC-001');s=advanceVoyageDay(s,'ot-vessel-001');expect(voyageForVessel(s,'ot-vessel-001')?.day).toBe(1);expect(voyageForVessel(s,'ot-vessel-002')?.day).toBe(0);s=advanceVoyageDay(s,'ot-vessel-001');expect(voyageForVessel(s,'ot-vessel-001')?.arrivalPending).toBe(true);const cash=s.cash;s=completeHarbourArrival(s,'ot-vessel-001',82);expect(s.cash).not.toBe(cash);expect(s.completedContracts).toContain('C-HAM-RTM-001');expect(voyageForVessel(s,'ot-vessel-001')).toBeNull();});
 it('advances all non-arrived vessels exactly one day',()=>{let s=createInitialState();s=acceptContract(s,'ot-vessel-001','C-HAM-NYC-001');s=acceptContract(s,'ot-vessel-002','C-RTM-NYC-001');s=advanceAllVoyagesDay(s);expect(s.voyages.map(v=>v.day)).toEqual([1,1]);});
 it('buys one market ship exactly once',()=>{let s=createInitialState();s={...s,cash:4_000_000};const offer=s.shipMarket[0],cash=s.cash;s=buyShip(s,offer.id);expect(s.vessels.some(v=>v.name===offer.vessel.name)).toBe(true);expect(s.cash).toBe(cash-offer.askingPrice);expect(()=>buyShip(s,offer.id)).toThrow();});
 it('refuels with local bunker price and caps at tank capacity',()=>{let s={...createInitialState(),cash:2_000_000};const before=s.vessels[0],cash=s.cash;s=refuelVessel(s,before.id,10_000);const after=s.vessels[0];expect(after.fuelTonnes).toBe(after.fuelCapacityTonnes);expect(s.cash).toBeLessThan(cash);});
 it('repairs only in capable ports and raises condition',()=>{let s={...createInitialState(),cash:2_000_000};s=repairVessel(s,'ot-vessel-001',95);expect(s.vessels[0].condition).toBe(95);const moved={...s,vessels:s.vessels.map(v=>v.id==='ot-vessel-001'?{...v,currentPort:'MIA' as const}:v)};expect(()=>repairVessel(moved,'ot-vessel-001',100)).toThrow();});
 it('market value reacts to condition and sale removes idle ship',()=>{let s=createInitialState();const v=s.vessels[0],high=vesselMarketValue(v,s.campaignDate),low=vesselMarketValue({...v,condition:40},s.campaignDate);expect(high).toBeGreaterThan(low);const cash=s.cash;s=sellVessel(s,'ot-vessel-001');expect(s.vessels.some(x=>x.id==='ot-vessel-001')).toBe(false);expect(s.cash).toBe(cash+high);});
 it('loan adds principal but company value reflects full liability',()=>{let s=createInitialState();const before=companyValue(s),cash=s.cash;s=takeLoan(s,'working-500');expect(s.cash).toBe(cash+500_000);expect(totalDebt(s)).toBeGreaterThan(500_000);expect(companyValue(s)).toBeLessThan(before);});
 it('repayment reduces cash and debt by the same amount',()=>{let s=takeLoan(createInitialState(),'working-500');const cash=s.cash,debt=totalDebt(s);s=repayLoanInstallment(s,s.loans[0].id);expect(cash-s.cash).toBe(debt-totalDebt(s));expect(s.loans[0].paymentsMade).toBe(1);});
 it('prevents duplicate active financing product',()=>{const s=takeLoan(createInitialState(),'fleet-1250');expect(()=>takeLoan(s,'fleet-1250')).toThrow();});
 it('does not apply an installment when cash is insufficient',()=>{let s=takeLoan(createInitialState(),'expansion-2500');s={...s,cash:0};const before=JSON.stringify(s);expect(()=>repayLoanInstallment(s,s.loans[0].id)).toThrow();expect(JSON.stringify(s)).toBe(before);});
});
