import { SHIP_CLASSES, bunkerPrice, createShipMarket, fuelPerDay, repairAvailable, repairCost, vesselFuelCapacity, vesselMarketValue } from './economy';
import { FINANCING_OFFERS, assessFinancingRisk, createLoan, nextInstallment, offerById, outstandingDebt, type FinanceRiskAssessment, type Loan } from './finance';
import { cargoCompatible, contractEconomics, rankContracts, repositionContract, routeRisk, type CargoType, type RouteRisk } from './market';
import { addCalendarDays, classUnlocked, eraForDate, nextEra as nextEraSpec, type EraSpec } from './era';

export type PortId='HAM'|'RTM'|'LON'|'ALG'|'NYC'|'SAV'|'MIA'|'STS'|'BUE'|'CPT'|'DUR'|'DXB'|'BOM'|'SIN'|'JKT'|'HKG'|'SHA'|'BUS'|'TYO'|'SYD';
export type ShipClassId='coaster'|'handysize'|'feeder'|'panamax';
export interface Contract{id:string;origin:PortId;destination:PortId;cargo:string;cargoType?:CargoType;tonnes:number;payout:number;days:number;deadlineDays:number;reposition?:boolean;}
export interface Vessel{id:string;name:string;classId:ShipClassId;className:string;builtYear:number;capacityTonnes:number;speedKnots:number;condition:number;fuelCapacityTonnes:number;fuelTonnes:number;currentPort:PortId|null;}
export interface ShipOffer{id:string;port:PortId;askingPrice:number;vessel:Vessel;}
export interface VoyageEvent{day:number;title:string;effect:string;}
export interface Voyage{id:string;vesselId:string;contractId:string;day:number;totalDays:number;fuelCost:number;maintenanceCost:number;eventCost:number;portCost?:number;acceptedPayout?:number;marketFactor?:number;risk?:RouteRisk;contractSnapshot?:Contract;fuelMultiplier?:number;maintenanceMultiplier?:number;seed:number;events:VoyageEvent[];arrivalPending?:boolean;reposition?:boolean;}
export interface GameState{schemaVersion:6;marketVersion:1;eraVersion:1;campaignDate:string;cash:number;reputation:number;vessels:Vessel[];contracts:Contract[];voyages:Voyage[];shipMarket:ShipOffer[];loans:Loan[];completedContracts:string[];transactionLog:string[];}

export const ports:Record<PortId,string>={HAM:'Hamburg',RTM:'Rotterdam',LON:'London Gateway',ALG:'Algeciras',NYC:'New York',SAV:'Savannah',MIA:'Miami',STS:'Santos',BUE:'Buenos Aires',CPT:'Cape Town',DUR:'Durban',DXB:'Jebel Ali',BOM:'Mumbai',SIN:'Singapore',JKT:'Jakarta',HKG:'Hong Kong',SHA:'Shanghai',BUS:'Busan',TYO:'Tokyo',SYD:'Sydney'};

export function seedContracts():Contract[]{return[
{id:'C-HAM-RTM-001',origin:'HAM',destination:'RTM',cargo:'Maschinenteile',cargoType:'general',tonnes:5_500,payout:78_000,days:2,deadlineDays:4},
{id:'C-HAM-NYC-001',origin:'HAM',destination:'NYC',cargo:'Stahlprodukte',cargoType:'general',tonnes:12_000,payout:244_000,days:8,deadlineDays:11},
{id:'C-HAM-SIN-001',origin:'HAM',destination:'SIN',cargo:'Chemikalien',cargoType:'chemical',tonnes:8_600,payout:421_000,days:18,deadlineDays:23},
{id:'C-RTM-NYC-001',origin:'RTM',destination:'NYC',cargo:'Anlagenbau',cargoType:'general',tonnes:7_200,payout:176_000,days:7,deadlineDays:10},
{id:'C-RTM-HAM-001',origin:'RTM',destination:'HAM',cargo:'Konsumgüter',cargoType:'general',tonnes:4_200,payout:59_000,days:2,deadlineDays:4},
{id:'C-NYC-HAM-001',origin:'NYC',destination:'HAM',cargo:'Industriegüter',cargoType:'general',tonnes:11_000,payout:231_000,days:8,deadlineDays:12},
{id:'C-NYC-RTM-001',origin:'NYC',destination:'RTM',cargo:'Papierprodukte',cargoType:'general',tonnes:8_000,payout:194_000,days:7,deadlineDays:10},
{id:'C-RTM-SIN-CON',origin:'RTM',destination:'SIN',cargo:'Containerladung',cargoType:'container',tonnes:12_500,payout:382_000,days:17,deadlineDays:20},
{id:'C-NYC-MIA-REF',origin:'NYC',destination:'MIA',cargo:'Kühlfrüchte',cargoType:'reefer',tonnes:5_800,payout:118_000,days:4,deadlineDays:5},
{id:'C-SIN-SHA-CON',origin:'SIN',destination:'SHA',cargo:'Containerladung',cargoType:'container',tonnes:13_000,payout:146_000,days:5,deadlineDays:7},
{id:'C-SHA-DXB-BULK',origin:'SHA',destination:'DXB',cargo:'Getreide',cargoType:'bulk',tonnes:34_000,payout:318_000,days:12,deadlineDays:16},
{id:'C-DXB-BOM-CHEM',origin:'DXB',destination:'BOM',cargo:'Chemikalien',cargoType:'chemical',tonnes:14_000,payout:164_000,days:4,deadlineDays:6},
{id:'C-CPT-STS-BULK',origin:'CPT',destination:'STS',cargo:'Eisenerz',cargoType:'bulk',tonnes:42_000,payout:356_000,days:11,deadlineDays:15},
{id:'C-TYO-SIN-CON',origin:'TYO',destination:'SIN',cargo:'Containerladung',cargoType:'container',tonnes:12_000,payout:205_000,days:7,deadlineDays:10}
];}

export function createInitialState():GameState{return{schemaVersion:6,marketVersion:1,eraVersion:1,campaignDate:'1970-01-05',cash:420_000,reputation:50,vessels:[
{id:'ot-vessel-001',name:'MS Pioneer',classId:'handysize',className:'Handysize',builtYear:1963,capacityTonnes:18_000,speedKnots:17,condition:84,fuelCapacityTonnes:1_050,fuelTonnes:820,currentPort:'HAM'},
{id:'ot-vessel-002',name:'Baltic Star',classId:'coaster',className:'Coaster',builtYear:1967,capacityTonnes:8_000,speedKnots:15,condition:91,fuelCapacityTonnes:620,fuelTonnes:540,currentPort:'RTM'},
{id:'ot-vessel-003',name:'Atlantic Spirit',classId:'handysize',className:'Handysize',builtYear:1965,capacityTonnes:18_000,speedKnots:17,condition:87,fuelCapacityTonnes:1_050,fuelTonnes:760,currentPort:'NYC'}],contracts:seedContracts(),voyages:[],shipMarket:createShipMarket(),loans:[],completedContracts:[],transactionLog:['Kampagne gestartet · Startkapital €420.000']};}

export function voyageForVessel(state:GameState,vesselId:string){return state.voyages.find(v=>v.vesselId===vesselId)??null;}
export function contractForVoyage(state:GameState,voyage:Voyage){return voyage.contractSnapshot??state.contracts.find(c=>c.id===voyage.contractId)??null;}
export function availableContractsForVessel(state:GameState,vesselId:string){const vessel=state.vessels.find(v=>v.id===vesselId);if(!vessel?.currentPort||voyageForVessel(state,vesselId))return[];const eligible=state.contracts.filter(c=>c.origin===vessel.currentPort&&cargoCompatible(c,vessel)).map(c=>{const e=contractEconomics(c,vessel,state.campaignDate);return{...c,payout:e.marketPayout,cargo:`${c.cargo} · ${e.label}`};});const reposition=repositionContract(vessel.currentPort,vessel,state.campaignDate);return[...rankContracts(eligible,vessel,state.campaignDate),reposition];}

function resolveContract(state:GameState,vessel:Vessel,contractId:string){const raw=state.contracts.find(c=>c.id===contractId);if(raw)return raw;if(contractId.startsWith('R-')&&vessel.currentPort){const r=repositionContract(vessel.currentPort,vessel,state.campaignDate);if(r.id===contractId)return r;}return null;}
export function acceptContract(state:GameState,vesselId:string,contractId:string):GameState{if(voyageForVessel(state,vesselId))throw new Error('Vessel already has an active voyage.');const vessel=state.vessels.find(v=>v.id===vesselId);if(!vessel)throw new Error('Vessel not found.');const contract=resolveContract(state,vessel,contractId);if(!contract)throw new Error('Contract not found.');if(vessel.currentPort!==contract.origin)throw new Error('Vessel is not at contract origin.');if(!contract.reposition&&!cargoCompatible(contract,vessel))throw new Error('Cargo is not compatible with this vessel.');const era=eraForDate(state.campaignDate),economics=contract.reposition?{marketFactor:1,marketPayout:0,portFees:Math.round((12_000+contract.days*900)*era.portMultiplier),risk:routeRisk(contract.origin,contract.destination)}:contractEconomics(contract,vessel,state.campaignDate),snapshot={...contract,payout:economics.marketPayout};return{...state,vessels:state.vessels.map(v=>v.id===vesselId?{...v,currentPort:null}:v),voyages:[...state.voyages,{id:`V-${contract.id}-${vesselId}`,vesselId,contractId:contract.id,day:0,totalDays:contract.days,fuelCost:0,maintenanceCost:0,eventCost:0,portCost:economics.portFees,acceptedPayout:economics.marketPayout,marketFactor:economics.marketFactor,risk:economics.risk,contractSnapshot:snapshot,fuelMultiplier:era.fuelMultiplier,maintenanceMultiplier:era.maintenanceMultiplier,reposition:Boolean(contract.reposition),seed:hashSeed(`${contract.id}:${vesselId}`),events:[]}],transactionLog:[`${vessel.name} · ${contract.reposition?'Leerfahrt':'Vertrag'} ${ports[contract.origin]} → ${ports[contract.destination]}${contract.reposition?'':` · Markt ${Math.round((economics.marketFactor-1)*100)}%`}`,...state.transactionLog]};}

export function advanceVoyageDay(state:GameState,vesselId:string):GameState{const voyage=voyageForVessel(state,vesselId);if(!voyage||voyage.arrivalPending)return state;const vessel=state.vessels.find(v=>v.id===vesselId)!;const contract=contractForVoyage(state,voyage);if(!contract)return state;const era=eraForDate(state.campaignDate),nextDay=voyage.day+1,burn=Math.max(1,fuelPerDay(vessel)*(voyage.fuelMultiplier??era.fuelMultiplier)),dailyFuel=Math.round(burn*bunkerPrice(contract.origin)),dailyMaintenance=Math.round((1_100+(100-vessel.condition)*22)*(voyage.maintenanceMultiplier??era.maintenanceMultiplier));let eventCost=voyage.eventCost,condition=Math.max(0,vessel.condition-.22),fuel=Math.max(0,vessel.fuelTonnes-burn),events=voyage.events;const roll=seededUnit(voyage.seed+nextDay*97),threshold=voyage.risk==='high'?.68:voyage.risk==='medium'?.76:.84;if(roll>threshold&&!events.some(e=>e.day===nextDay)){const multiplier=voyage.risk==='high'?1.5:voyage.risk==='medium'?1.15:.85,cost=Math.round((8_000+Math.floor(roll*8_000))*multiplier);eventCost+=cost;condition=Math.max(0,condition-(voyage.risk==='high'?1.5:1.1));events=[...events,{day:nextDay,title:'Schwere See',effect:`Zusatzkosten €${cost.toLocaleString('de-DE')} · Zustand belastet`}];}const arrivalPending=nextDay>=voyage.totalDays,updated={...voyage,day:nextDay,fuelCost:voyage.fuelCost+dailyFuel,maintenanceCost:voyage.maintenanceCost+dailyMaintenance,eventCost,events,arrivalPending},progressed={...state,vessels:state.vessels.map(v=>v.id===vesselId?{...v,condition,fuelTonnes:fuel}:v),voyages:state.voyages.map(v=>v.id===voyage.id?updated:v)};return arrivalPending?{...progressed,transactionLog:[`${vessel.name} vor ${ports[contract.destination]} · Hafenmanöver erforderlich`,...progressed.transactionLog]}:progressed;}
export function advanceAllVoyagesDay(state:GameState):GameState{const ids=state.voyages.filter(v=>!v.arrivalPending).map(v=>v.vesselId),progressed=ids.reduce((s,id)=>advanceVoyageDay(s,id),state);return ids.length?{...progressed,campaignDate:addCalendarDays(progressed.campaignDate,1)}:progressed;}

export function completeHarbourArrival(state:GameState,vesselId:string,condition:number):GameState{const voyage=voyageForVessel(state,vesselId);if(!voyage?.arrivalPending)throw new Error('No harbour arrival pending.');const contract=contractForVoyage(state,voyage);if(!contract)throw new Error('Contract not found.');const vessel=state.vessels.find(v=>v.id===vesselId)!,costs=voyage.fuelCost+voyage.maintenanceCost+voyage.eventCost+(voyage.portCost??0),payout=voyage.acceptedPayout??contract.payout,net=payout-costs,isCargo=!voyage.reposition;return{...state,cash:state.cash+net,reputation:isCargo?Math.min(100,state.reputation+2):state.reputation,vessels:state.vessels.map(v=>v.id===vesselId?{...v,condition:Math.max(0,Math.min(v.condition,condition)),currentPort:contract.destination}:v),voyages:state.voyages.filter(v=>v.id!==voyage.id),completedContracts:isCargo?[...state.completedContracts,contract.id]:state.completedContracts,contracts:isCargo?state.contracts.filter(c=>c.id!==contract.id):state.contracts,transactionLog:[`${vessel.name} festgemacht · ${voyage.reposition?'Leerfahrt':'Fracht'} Netto ${currency(net)}`,`Umsatz ${currency(payout)} · Fuel/Wartung/Event/Hafen ${currency(costs)}`,...state.transactionLog]};}

function serviceableVessel(state:GameState,vesselId:string):Vessel{const vessel=state.vessels.find(v=>v.id===vesselId);if(!vessel)throw new Error('Vessel not found.');if(!vessel.currentPort||voyageForVessel(state,vesselId))throw new Error('Vessel must be idle in port.');return vessel;}
export function refuelVessel(state:GameState,vesselId:string,tonnes:number):GameState{const vessel=serviceableVessel(state,vesselId),capacity=vesselFuelCapacity(vessel),amount=Math.max(0,Math.min(tonnes,capacity-vessel.fuelTonnes));if(amount<=0)return state;const price=bunkerPrice(vessel.currentPort!),cost=Math.round(amount*price);if(cost>state.cash)throw new Error('Insufficient cash.');return{...state,cash:state.cash-cost,vessels:state.vessels.map(v=>v.id===vesselId?{...v,fuelTonnes:v.fuelTonnes+amount}:v),transactionLog:[`${vessel.name} · ${Math.round(amount)} t gebunkert · ${currency(cost)}`,...state.transactionLog]};}
export function repairVessel(state:GameState,vesselId:string,targetCondition:number):GameState{const vessel=serviceableVessel(state,vesselId);if(!repairAvailable(vessel.currentPort!))throw new Error('Repairs not available in this port.');const target=Math.max(vessel.condition,Math.min(100,targetCondition)),cost=repairCost(vessel,target);if(cost<=0)return state;if(cost>state.cash)throw new Error('Insufficient cash.');return{...state,cash:state.cash-cost,vessels:state.vessels.map(v=>v.id===vesselId?{...v,condition:target}:v),transactionLog:[`${vessel.name} · Reparatur auf ${target.toFixed(0)} % · ${currency(cost)}`,...state.transactionLog]};}
export function buyShip(state:GameState,offerId:string):GameState{const offer=state.shipMarket.find(o=>o.id===offerId);if(!offer)throw new Error('Offer not found.');if(!classUnlocked(offer.vessel.classId,state.campaignDate))throw new Error(`${offer.vessel.className} ist in dieser Epoche noch nicht verfügbar.`);if(offer.askingPrice>state.cash)throw new Error('Insufficient cash.');const vessel={...offer.vessel,id:`owned-${offer.vessel.id}-${state.vessels.length+1}`};return{...state,cash:state.cash-offer.askingPrice,vessels:[...state.vessels,vessel],shipMarket:state.shipMarket.filter(o=>o.id!==offerId),transactionLog:[`${vessel.name} gekauft · ${ports[offer.port]} · ${currency(offer.askingPrice)}`,...state.transactionLog]};}
export function sellVessel(state:GameState,vesselId:string):GameState{if(state.vessels.length<=1)throw new Error('Cannot sell last vessel.');const vessel=serviceableVessel(state,vesselId),value=vesselMarketValue(vessel,state.campaignDate);return{...state,cash:state.cash+value,vessels:state.vessels.filter(v=>v.id!==vesselId),transactionLog:[`${vessel.name} verkauft · ${currency(value)}`,...state.transactionLog]};}
export function takeLoan(state:GameState,offerId:string):GameState{const offer=offerById(offerId);if(!offer)throw new Error('Financing offer not found.');if(state.loans.length>=3)throw new Error('Maximum of three active loans reached.');if(state.loans.some(l=>l.offerId===offerId))throw new Error('This financing product is already active.');const loan=createLoan(offer,state.loans.length+1);return{...state,cash:state.cash+loan.principal,loans:[...state.loans,loan],transactionLog:[`${loan.name} aufgenommen · Auszahlung ${currency(loan.principal)} · Rückzahlung ${currency(loan.totalRepayment)}`,...state.transactionLog]};}
export function repayLoanInstallment(state:GameState,loanId:string):GameState{const loan=state.loans.find(l=>l.id===loanId);if(!loan)throw new Error('Loan not found.');const payment=nextInstallment(loan);if(payment<=0)throw new Error('Loan already repaid.');if(payment>state.cash)throw new Error('Insufficient cash for installment.');const balance=Math.max(0,loan.balance-payment),paymentsMade=loan.paymentsMade+1,loans=balance===0?state.loans.filter(l=>l.id!==loanId):state.loans.map(l=>l.id===loanId?{...l,balance,paymentsMade}:l);return{...state,cash:state.cash-payment,loans,transactionLog:[`${loan.name} · Rate ${paymentsMade}/${loan.installments} · ${currency(payment)}${balance===0?' · vollständig getilgt':''}`,...state.transactionLog]};}

export function currentEra(state:GameState):EraSpec{return eraForDate(state.campaignDate);}
export function eraTransition(state:GameState){const target=nextEraSpec(state.campaignDate);if(!target)return null;const fromYear=Number(state.campaignDate.slice(0,4))||1970,years=Math.max(1,target.fromYear-fromYear),cost=years*state.vessels.length*6_000;return{target,years,cost};}
export function advanceEra(state:GameState):GameState{if(state.voyages.length)throw new Error('Epoche kann nur ohne laufende Reisen fortgeschrieben werden.');const transition=eraTransition(state);if(!transition)throw new Error('Die Zukunftsepoche ist bereits erreicht.');if(transition.cost>state.cash)throw new Error('Nicht genügend Cash für Flotten-Overhead der Fortschreibung.');const conditionLoss=Math.min(12,transition.years*.35),date=`${transition.target.fromYear}-01-01`;return{...state,campaignDate:date,cash:state.cash-transition.cost,vessels:state.vessels.map(v=>({...v,condition:Math.max(35,v.condition-conditionLoss)})),transactionLog:[`Neue Epoche: ${transition.target.name} · ${transition.target.fromYear} · Overhead ${currency(transition.cost)}`,`Zeitsprung ${transition.years} Jahre · Flottenzustand -${conditionLoss.toFixed(1)} %`,...state.transactionLog]};}
export function financingRisk(state:GameState,offerId:string):FinanceRiskAssessment{const offer=offerById(offerId);if(!offer)throw new Error('Financing offer not found.');return assessFinancingRisk(state.cash,state.vessels.length,state.loans,offer);}
export function totalDebt(state:GameState){return outstandingDebt(state.loans);}
export function companyValue(state:GameState){return state.cash+state.vessels.reduce((sum,v)=>sum+vesselMarketValue(v,state.campaignDate),0)-totalDebt(state);}
export function attentionCount(state:GameState){return state.vessels.filter(v=>v.condition<80||v.fuelTonnes<vesselFuelCapacity(v)*.25||voyageForVessel(state,v.id)?.arrivalPending).length+(state.loans.some(l=>nextInstallment(l)>state.cash)?1:0);}
export function currency(value:number){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(value);}
export { SHIP_CLASSES, bunkerPrice, repairAvailable, repairCost, vesselFuelCapacity, vesselMarketValue } from './economy';
export { FINANCING_OFFERS, nextInstallment, previewLoan } from './finance';
export { classUnlocked } from './era';
export type { Loan } from './finance';
function hashSeed(input:string){let h=2166136261;for(const ch of input)h=Math.imul(h^ch.charCodeAt(0),16777619);return h>>>0;}
function seededUnit(seed:number){let x=seed>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967295;}
