import{describe,expect,it}from'vitest';
import{acceptContract,advanceAllVoyagesDay,advanceVoyageDay,buyShip,completeHarbourArrival,createInitialState,refuelVessel,repairVessel,sellVessel,vesselMarketValue,voyageForVessel}from'./domain';

describe('fleet and commerce domain',()=>{
 it('runs voyages independently and requires harbour settlement',()=>{let s=createInitialState();s=acceptContract(s,'ot-vessel-001','C-HAM-RTM-001');s=acceptContract(s,'ot-vessel-002','C-RTM-NYC-001');s=advanceVoyageDay(s,'ot-vessel-001');expect(voyageForVessel(s,'ot-vessel-001')?.day).toBe(1);expect(voyageForVessel(s,'ot-vessel-002')?.day).toBe(0);s=advanceVoyageDay(s,'ot-vessel-001');expect(voyageForVessel(s,'ot-vessel-001')?.arrivalPending).toBe(true);const cash=s.cash;s=completeHarbourArrival(s,'ot-vessel-001',82);expect(s.cash).toBeGreaterThan(cash);expect(s.completedContracts).toContain('C-HAM-RTM-001');});
 it('advances all non-arrived vessels exactly one day',()=>{let s=createInitialState();s=acceptContract(s,'ot-vessel-001','C-HAM-NYC-001');s=acceptContract(s,'ot-vessel-002','C-RTM-NYC-001');s=advanceAllVoyagesDay(s);expect(s.voyages.map(v=>v.day)).toEqual([1,1]);});
 it('buys one market ship exactly once',()=>{let s=createInitialState();s={...s,cash:4_000_000};const offer=s.shipMarket[0],cash=s.cash;s=buyShip(s,offer.id);expect(s.vessels.some(v=>v.name===offer.vessel.name)).toBe(true);expect(s.cash).toBe(cash-offer.askingPrice);expect(()=>buyShip(s,offer.id)).toThrow();});
 it('refuels with local bunker price and caps at tank capacity',()=>{let s={...createInitialState(),cash:2_000_000};const before=s.vessels[0],cash=s.cash;s=refuelVessel(s,before.id,10_000);const after=s.vessels[0];expect(after.fuelTonnes).toBe(after.fuelCapacityTonnes);expect(s.cash).toBeLessThan(cash);});
 it('repairs only in capable ports and raises condition',()=>{let s={...createInitialState(),cash:2_000_000};s=repairVessel(s,'ot-vessel-001',95);expect(s.vessels[0].condition).toBe(95);const moved={...s,vessels:s.vessels.map(v=>v.id==='ot-vessel-001'?{...v,currentPort:'MIA' as const}:v)};expect(()=>repairVessel(moved,'ot-vessel-001',100)).toThrow();});
 it('market value reacts to condition and sale removes idle ship',()=>{let s=createInitialState();const v=s.vessels[0],high=vesselMarketValue(v,s.campaignDate),low=vesselMarketValue({...v,condition:40},s.campaignDate);expect(high).toBeGreaterThan(low);const cash=s.cash;s=sellVessel(s,'ot-vessel-001');expect(s.vessels.some(x=>x.id==='ot-vessel-001')).toBe(false);expect(s.cash).toBe(cash+high);});
});
