import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{acceptContract,advanceAllVoyagesDay,attentionCount,availableContractsForVessel,companyValue,completeHarbourArrival,contractForVoyage,createInitialState,currency,ports,voyageForVessel,type GameState,type PortId,type Vessel}from'./domain';
import{HARBOUR,initialHarbourState,stepHarbour,type HarbourInput,type HarbourState}from'./harbour';
import{etaDays,mapPorts,portById,project,vesselMapPosition,vesselsAtPort,voyageProgress}from'./map';
import{clearState,loadState,saveState}from'./storage';
import'./styles.css';

type Tab='market'|'fleet'|'map'|'company';
type MapSelection={kind:'vessel';id:string}|{kind:'port';id:PortId};

function App(){
 const[state,setState]=useState<GameState>(()=>loadState(localStorage)??createInitialState());
 const[tab,setTab]=useState<Tab>('fleet'); const[selected,setSelected]=useState(state.vessels[0]?.id??'');
 const[mapSelection,setMapSelection]=useState<MapSelection>({kind:'vessel',id:state.vessels[0]?.id??''}); const[mapZoom,setMapZoom]=useState(1); const[harbourVessel,setHarbourVessel]=useState<string|null>(null);
 useEffect(()=>saveState(localStorage,state),[state]);
 const vessel=useMemo(()=>state.vessels.find(v=>v.id===selected)??state.vessels[0],[state.vessels,selected]);
 function start(vesselId:string,contractId:string){setState(s=>acceptContract(s,vesselId,contractId));setSelected(vesselId);setMapSelection({kind:'vessel',id:vesselId});setTab('fleet');}
 function reset(){if(!confirm('Lokalen Spielstand wirklich löschen und neu beginnen?'))return;clearState(localStorage);const fresh=createInitialState();setState(fresh);setSelected(fresh.vessels[0].id);setMapSelection({kind:'vessel',id:fresh.vessels[0].id});setTab('fleet');}
 if(harbourVessel){const hv=state.vessels.find(v=>v.id===harbourVessel),voyage=voyageForVessel(state,harbourVessel),contract=voyage?contractForVoyage(state,voyage):null;if(hv&&voyage?.arrivalPending&&contract)return <HarbourScreen vessel={hv} destination={ports[contract.destination]} onLater={()=>setHarbourVessel(null)} onComplete={condition=>{setState(s=>completeHarbourArrival(s,harbourVessel,condition));setSelected(harbourVessel);setHarbourVessel(null);setTab('fleet');}}/>;setHarbourVessel(null);}
 return <div className="app-shell"><header className="topbar"><div><span className="eyebrow">FLEET COMMAND</span><h1>Ocean Trader</h1></div><div className="date-pill">{state.campaignDate}</div></header><main>
 <section className="summary-strip" aria-label="Unternehmensübersicht"><Summary label="Cash" value={currency(state.cash)}/><Summary label="Aktiv" value={`${state.voyages.length}/${state.vessels.length}`}/><Summary label="Achtung" value={`${attentionCount(state)}`}/></section>
 {tab==='fleet'&&<FleetView state={state} vessel={vessel} selected={selected} onSelect={setSelected} onAdvance={()=>setState(advanceAllVoyagesDay)} onHarbour={setHarbourVessel}/>} 
 {tab==='market'&&<MarketView state={state} onStart={start}/>} {tab==='map'&&<MapView state={state} selection={mapSelection} onSelect={setMapSelection} zoom={mapZoom} setZoom={setMapZoom}/>} 
 {tab==='company'&&<section><span className="eyebrow">COMPANY</span><h2>Northstar Shipping</h2><div className="company-grid"><Summary label="Flottenwert" value={currency(companyValue(state))}/><Summary label="Ruf" value={`${state.reputation}/100`}/><Summary label="Abgeschlossen" value={`${state.completedContracts.length}`}/></div><h3 className="log-title">Letzte Buchungen</h3><div className="log">{state.transactionLog.slice(0,8).map((l,i)=><div key={i}>{l}</div>)}</div><button className="secondary danger" onClick={reset}>Spielstand zurücksetzen</button></section>}
 </main><footer className="legal-footer" aria-label="Rechtliche Informationen"><a href="/impressum.html">Impressum</a><span>·</span><a href="/datenschutz.html">Datenschutz</a></footer><nav className="bottom-nav" aria-label="Hauptnavigation"><Nav active={tab==='market'} onClick={()=>setTab('market')} icon="◫" label="Markt"/><Nav active={tab==='fleet'} onClick={()=>setTab('fleet')} icon="≋" label="Flotte" badge={Boolean(state.voyages.length)}/><Nav active={tab==='map'} onClick={()=>setTab('map')} icon="◎" label="Karte"/><Nav active={tab==='company'} onClick={()=>setTab('company')} icon="●" label="Firma"/></nav></div>;
}

function HarbourScreen({vessel,destination,onLater,onComplete}:{vessel:Vessel;destination:string;onLater:()=>void;onComplete:(condition:number)=>void}){
 const[sim,setSim]=useState<HarbourState>(()=>initialHarbourState(vessel.condition)); const input=useRef<HarbourInput>({throttle:0,rudder:0});
 useEffect(()=>{const timer=window.setInterval(()=>setSim(s=>stepHarbour(s,input.current,.05)),50);return()=>clearInterval(timer)},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='w'||e.key==='ArrowUp')input.current.throttle=.7;if(e.key==='s'||e.key==='ArrowDown')input.current.throttle=-.55;if(e.key==='a'||e.key==='ArrowLeft')input.current.rudder=-1;if(e.key==='d'||e.key==='ArrowRight')input.current.rudder=1;if(e.key===' ')input.current={throttle:0,rudder:0};};const up=(e:KeyboardEvent)=>{if(['a','d','ArrowLeft','ArrowRight'].includes(e.key))input.current.rudder=0};addEventListener('keydown',key);addEventListener('keyup',up);return()=>{removeEventListener('keydown',key);removeEventListener('keyup',up)}},[]);
 const ship=`translate(${sim.x} ${sim.y}) rotate(${sim.heading*180/Math.PI})`;
 return <div className="harbour-shell"><header className="harbour-header"><button className="ghost-action" onClick={onLater}>← Später</button><div><span className="eyebrow">ARRIVAL · {destination.toUpperCase()}</span><h1>{vessel.name}</h1></div><span className={sim.docked?'status port':'status sailing'}>{sim.docked?'FEST':'MANÖVER'}</span></header>
 <section className="harbour-hud"><Summary label="Fahrt" value={`${sim.speed.toFixed(1)} kn`}/><Summary label="Zustand" value={`${sim.condition.toFixed(1)} %`}/><Summary label="Kontakt" value={`${sim.collisions+sim.groundings}`}/></section>
 <div className="harbour-stage"><svg viewBox="0 0 1200 720" aria-label="Hafenmanöver"><rect width="1200" height="720" className="harbour-water"/><rect x={HARBOUR.berth.x} y={HARBOUR.berth.y} width={HARBOUR.berth.w} height={HARBOUR.berth.h} className="berth"/>{HARBOUR.shallow.map((r,i)=><rect key={`s${i}`} {...r} className="shallow"/>)}{HARBOUR.quays.map((r,i)=><rect key={`q${i}`} {...r} className="quay"/>)}{HARBOUR.breakwaters.map((r,i)=><rect key={`b${i}`} {...r} className="breakwater"/>)}<g transform={ship} className="harbour-ship"><path d="M 34 0 L 18 -11 L -28 -11 L -34 0 L -28 11 L 18 11 Z"/><line x1="-10" y1="0" x2="18" y2="0"/></g><text x="945" y="173" className="berth-label">LIEGEPLATZ</text></svg></div>
 <div className={sim.docked?'harbour-message success':'harbour-message'}>{sim.message}</div>
 {!sim.docked?<div className="helm"><div className="throttle"><span>MASCHINE</span><button onClick={()=>input.current.throttle=.7}>Voraus</button><button onClick={()=>input.current.throttle=0}>Stopp</button><button onClick={()=>input.current.throttle=-.55}>Zurück</button></div><div className="rudder"><span>RUDER</span><button onPointerDown={()=>input.current.rudder=-1} onPointerUp={()=>input.current.rudder=0} onPointerCancel={()=>input.current.rudder=0}>◀ Backbord</button><button onClick={()=>input.current.rudder=0}>Mitte</button><button onPointerDown={()=>input.current.rudder=1} onPointerUp={()=>input.current.rudder=0} onPointerCancel={()=>input.current.rudder=0}>Steuerbord ▶</button></div></div>:<button className="primary settlement" onClick={()=>onComplete(sim.condition)}>Festmachen & Fracht abrechnen</button>}
 </div>;
}

function FleetView({state,vessel,selected,onSelect,onAdvance,onHarbour}:{state:GameState;vessel:Vessel|undefined;selected:string;onSelect:(id:string)=>void;onAdvance:()=>void;onHarbour:(id:string)=>void}){const voyage=vessel?voyageForVessel(state,vessel.id):null;const contract=voyage?contractForVoyage(state,voyage):null;return <section><div className="section-head"><div><span className="eyebrow">FLEET</span><h2>{state.vessels.length} Schiffe · {state.voyages.length} unterwegs</h2></div><button className="compact-action" disabled={!state.voyages.some(v=>!v.arrivalPending)} onClick={onAdvance}>+ 1 Tag</button></div><div className="fleet-list">{state.vessels.map(v=><FleetRow key={v.id} state={state} vessel={v} selected={v.id===selected} onClick={()=>onSelect(v.id)}/>)}</div>{vessel&&<article className="detail-card"><div className="detail-head"><div><span className="label">Ausgewählt</span><h3>{vessel.name}</h3><p>{vessel.className} · {vessel.capacityTonnes.toLocaleString('de-DE')} t</p></div><Status state={state} vessel={vessel}/></div>{voyage&&contract?<><div className="route large"><strong>{ports[contract.origin]}</strong><span>→</span><strong>{ports[contract.destination]}</strong></div><div className="progress-track"><i style={{width:`${Math.round(voyageProgress(voyage)*100)}%`}}/></div><div className="voyage-grid"><Summary label="Tag" value={`${voyage.day}/${voyage.totalDays}`}/><Summary label="ETA" value={voyage.arrivalPending?'Hafen':`${etaDays(voyage)} Tage`}/><Summary label="Zustand" value={`${vessel.condition.toFixed(1)} %`}/></div>{voyage.arrivalPending&&<button className="primary harbour-cta" onClick={()=>onHarbour(vessel.id)}>Hafenmanöver starten</button>}{voyage.events.length>0&&<div className="event-box"><strong>{voyage.events.at(-1)?.title}</strong><span>{voyage.events.at(-1)?.effect}</span></div>}</>:<div className="port-ready">Bereit in <strong>{vessel.currentPort?ports[vessel.currentPort]:'—'}</strong>. Passende Fracht im Markt wählen.</div>}</article>}</section>}
function MarketView({state,onStart}:{state:GameState;onStart:(vesselId:string,contractId:string)=>void}){return <section><span className="eyebrow">FREIGHT MARKET</span><h2>Aufträge für deine verfügbaren Schiffe</h2><div className="contract-list">{state.vessels.flatMap(v=>availableContractsForVessel(state,v.id).map(c=><article className="contract-card" key={`${v.id}-${c.id}`}><div className="assignment"><span>{v.name}</span><span>{v.capacityTonnes.toLocaleString('de-DE')} t</span></div><div className="route"><strong>{ports[c.origin]}</strong><span>→</span><strong>{ports[c.destination]}</strong></div><h3>{c.cargo}</h3><div className="metrics"><span>{c.tonnes.toLocaleString('de-DE')} t</span><span>{c.days} Tage</span><span>Frist {c.deadlineDays} T.</span></div><div className="payout"><span>Fracht</span><strong>{currency(c.payout)}</strong></div><button className="primary" onClick={()=>onStart(v.id,c.id)}>Mit {v.name} annehmen</button></article>))}{state.vessels.every(v=>availableContractsForVessel(state,v.id).length===0)&&<div className="empty">Keine passende Fracht für verfügbare Schiffe.</div>}</div></section>}
function MapView({state,selection,onSelect,zoom,setZoom}:{state:GameState;selection:MapSelection;onSelect:(s:MapSelection)=>void;zoom:number;setZoom:(z:number)=>void}){const selectedVessel=selection.kind==='vessel'?state.vessels.find(v=>v.id===selection.id):undefined;const selectedPort=selection.kind==='port'?portById(selection.id):undefined;return <section><div className="section-head map-head"><div><span className="eyebrow">WORLD OPERATIONS</span><h2>20 Häfen · {state.voyages.length} aktive Routen</h2></div><div className="zoom-controls" aria-label="Kartenzoom"><button onClick={()=>setZoom(Math.max(1,zoom-.35))} disabled={zoom<=1}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(Math.min(2.4,zoom+.35))} disabled={zoom>=2.4}>+</button></div></div><div className="map-scroll"><div className="map-scale" style={{width:`${640*zoom}px`}}><svg className="world-map" viewBox="0 0 1000 520"> <rect width="1000" height="520" className="sea"/>{[-120,-60,0,60,120].map(lon=>{const p=project(0,lon);return <line key={lon} x1={p.x} x2={p.x} y1="0" y2="520" className="grid-line"/>})}{[-60,-30,0,30,60].map(lat=>{const p=project(lat,0);return <line key={lat} x1="0" x2="1000" y1={p.y} y2={p.y} className="grid-line"/>})}{state.voyages.map(v=>{const c=contractForVoyage(state,v);if(!c)return null;const a=project(portById(c.origin).lat,portById(c.origin).lon),b=project(portById(c.destination).lat,portById(c.destination).lon);return <line key={v.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} className="route-line" onClick={()=>onSelect({kind:'vessel',id:v.vesselId})}/>})}{mapPorts.map(p=>{const q=project(p.lat,p.lon),active=selection.kind==='port'&&selection.id===p.id;return <g key={p.id} className={active?'port-node selected':'port-node'} onClick={()=>onSelect({kind:'port',id:p.id})}><circle cx={q.x} cy={q.y} r={active?7:4}/>{active&&<text x={q.x+10} y={q.y-9}>{p.name}</text>}</g>})}{state.vessels.map(v=>{const q=vesselMapPosition(state,v),active=selection.kind==='vessel'&&selection.id===v.id;return <g key={v.id} className={active?'vessel-node selected':'vessel-node'} onClick={()=>onSelect({kind:'vessel',id:v.id})}><circle cx={q.x} cy={q.y} r={active?10:8}/><path d={`M ${q.x-5} ${q.y} L ${q.x+7} ${q.y-4} L ${q.x+4} ${q.y+4} Z`}/>{active&&<text x={q.x+13} y={q.y+18}>{v.name}</text>}</g>})}</svg></div></div><div className="map-hint">Ziehen · +/− zoomen · Hafen oder Schiff antippen</div>{selectedVessel&&<MapVesselCard state={state} vessel={selectedVessel}/>} {selectedPort&&<MapPortCard state={state} portId={selectedPort.id}/>}<div className="port-strip">{mapPorts.map(p=><button key={p.id} className={selection.kind==='port'&&selection.id===p.id?'port-chip active':'port-chip'} onClick={()=>onSelect({kind:'port',id:p.id})}>{p.name}</button>)}</div></section>}
function MapVesselCard({state,vessel}:{state:GameState;vessel:Vessel}){const voyage=voyageForVessel(state,vessel.id),contract=voyage?contractForVoyage(state,voyage):null;return <article className="map-detail"><div><span className="label">Schiff</span><h3>{vessel.name}</h3></div><Status state={state} vessel={vessel}/>{voyage&&contract?<><div className="map-detail-route">{ports[contract.origin]} → {ports[contract.destination]}</div><div className="map-detail-metrics"><span>{voyage.arrivalPending?'Ankunft':'Unterwegs'}</span><span>ETA {etaDays(voyage)} T.</span><span>{vessel.speedKnots} kn</span></div></>:<div className="map-detail-route">{vessel.currentPort?ports[vessel.currentPort]:'Position unbekannt'} · verfügbar</div>}</article>}
function MapPortCard({state,portId}:{state:GameState;portId:PortId}){const p=portById(portId),local=vesselsAtPort(state,portId),offers=state.contracts.filter(c=>c.origin===portId).length;return <article className="map-detail"><div><span className="label">Hafen</span><h3>{p.name}</h3><p>{p.country}</p></div><div className="map-detail-metrics"><span>{local.length} Schiffe</span><span>{offers} Aufträge</span><span>{p.lat.toFixed(1)}°, {p.lon.toFixed(1)}°</span></div></article>}
function FleetRow({state,vessel,selected,onClick}:{state:GameState;vessel:Vessel;selected:boolean;onClick:()=>void}){const voyage=voyageForVessel(state,vessel.id),contract=voyage?contractForVoyage(state,voyage):null;return <button className={selected?'fleet-row selected':'fleet-row'} onClick={onClick}><span className="fleet-main"><strong>{vessel.name}</strong><small>{voyage&&contract?`${ports[contract.origin]} → ${ports[contract.destination]}`:`${vessel.currentPort?ports[vessel.currentPort]:'Auf See'} · verfügbar`}</small></span><span className="fleet-meta"><b>{voyage?.arrivalPending?'HAFEN':voyage?`${Math.round(voyageProgress(voyage)*100)}%`:'PORT'}</b><small>{vessel.condition.toFixed(0)}%</small></span></button>}
function Status({state,vessel}:{state:GameState;vessel:Vessel}){const voyage=voyageForVessel(state,vessel.id);return <span className={voyage?.arrivalPending?'status arrival':voyage?'status sailing':'status port'}>{voyage?.arrivalPending?'MANÖVER':voyage?'AUF SEE':'IM HAFEN'}</span>}
function Summary({label,value}:{label:string;value:string}){return <div className="summary"><span>{label}</span><strong>{value}</strong></div>}
function Nav({active,onClick,icon,label,badge}:{active:boolean;onClick:()=>void;icon:string;label:string;badge?:boolean}){return <button className={active?'nav active':'nav'} onClick={onClick}><span className="nav-icon">{icon}{badge&&<i/>}</span><span>{label}</span></button>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
