import type { Contract, PortId, Vessel } from './domain';
import { bunkerPrice, fuelPerDay } from './economy';

export type CargoType='general'|'bulk'|'chemical'|'container'|'reefer';
export type RouteRisk='low'|'medium'|'high';
export interface ContractEconomics{marketFactor:number;marketPayout:number;portFees:number;estimatedFuel:number;estimatedMaintenance:number;expectedNet:number;risk:RouteRisk;label:string;}

const PORTS:Record<PortId,{lat:number;lon:number;fee:number;handling:number;hub:boolean}>={
 HAM:{lat:53.55,lon:9.99,fee:9000,handling:.70,hub:true},RTM:{lat:51.92,lon:4.48,fee:8500,handling:.62,hub:true},LON:{lat:51.50,lon:.48,fee:10500,handling:.76,hub:false},ALG:{lat:36.13,lon:-5.45,fee:7200,handling:.55,hub:true},NYC:{lat:40.71,lon:-74.01,fee:12500,handling:.82,hub:true},SAV:{lat:32.08,lon:-81.09,fee:7600,handling:.58,hub:false},MIA:{lat:25.76,lon:-80.19,fee:9200,handling:.74,hub:false},STS:{lat:-23.96,lon:-46.33,fee:7400,handling:.52,hub:true},BUE:{lat:-34.60,lon:-58.38,fee:6900,handling:.49,hub:false},CPT:{lat:-33.92,lon:18.42,fee:7200,handling:.56,hub:true},DUR:{lat:-29.86,lon:31.02,fee:6800,handling:.50,hub:false},DXB:{lat:25.01,lon:55.06,fee:8100,handling:.61,hub:true},BOM:{lat:18.95,lon:72.84,fee:6500,handling:.48,hub:false},SIN:{lat:1.26,lon:103.84,fee:7800,handling:.57,hub:true},JKT:{lat:-6.10,lon:106.88,fee:6100,handling:.45,hub:false},HKG:{lat:22.30,lon:114.17,fee:9000,handling:.66,hub:true},SHA:{lat:31.23,lon:121.47,fee:8200,handling:.59,hub:true},BUS:{lat:35.10,lon:129.04,fee:7600,handling:.54,hub:false},TYO:{lat:35.68,lon:139.76,fee:11200,handling:.79,hub:true},SYD:{lat:-33.87,lon:151.21,fee:9800,handling:.71,hub:true}
};
const HUBS=(Object.keys(PORTS) as PortId[]).filter(p=>PORTS[p].hub);
const ALLOWED:Record<CargoType,Vessel['classId'][]>= {general:['coaster','handysize','feeder','panamax'],bulk:['handysize','panamax'],chemical:['handysize','panamax'],container:['feeder','panamax'],reefer:['coaster','feeder']};

function hash(input:string){let h=2166136261;for(const ch of input)h=Math.imul(h^ch.charCodeAt(0),16777619);return h>>>0;}
function radians(v:number){return v*Math.PI/180;}
export function routeDistanceNm(a:PortId,b:PortId){const p=PORTS[a],q=PORTS[b],dLat=radians(q.lat-p.lat),dLon=radians(q.lon-p.lon),x=Math.sin(dLat/2)**2+Math.cos(radians(p.lat))*Math.cos(radians(q.lat))*Math.sin(dLon/2)**2;return Math.round(3440.065*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x)));}
export function routeDays(a:PortId,b:PortId,vessel:Vessel){return Math.max(1,Math.ceil(routeDistanceNm(a,b)/(vessel.speedKnots*24)*1.12));}
export function cargoType(contract:Contract):CargoType{if(contract.cargoType)return contract.cargoType;const s=contract.cargo.toLowerCase();if(s.includes('chem'))return'chemical';if(s.includes('container'))return'container';if(s.includes('kühl')||s.includes('frucht'))return'reefer';if(s.includes('erz')||s.includes('kohle')||s.includes('getreide'))return'bulk';return'general';}
export function cargoCompatible(contract:Contract,vessel:Vessel){return ALLOWED[cargoType(contract)].includes(vessel.classId)&&contract.tonnes<=vessel.capacityTonnes;}
export function marketFactor(contract:Contract,date:string){const month=(Number(date.slice(5,7))||1)-1,seed=hash(`${contract.id}:${contract.origin}:${contract.destination}`)%12;const wave=Math.sin((month+seed)/12*Math.PI*2);const noise=((hash(`${contract.id}:${date.slice(0,7)}`)%21)-10)/100;return Math.max(.76,Math.min(1.28,1+wave*.16+noise));}
export function portFees(contract:Contract){const a=PORTS[contract.origin],b=PORTS[contract.destination];return Math.round(a.fee+b.fee+contract.tonnes*(a.handling+b.handling));}
export function routeRisk(origin:PortId,destination:PortId):RouteRisk{const d=routeDistanceNm(origin,destination);if(d>7000)return'high';if(d>3000)return'medium';return'low';}
export function contractEconomics(contract:Contract,vessel:Vessel,date:string):ContractEconomics{const factor=marketFactor(contract,date),marketPayout=Math.round(contract.payout*factor),fees=portFees(contract),fuel=Math.round(fuelPerDay(vessel)*contract.days*bunkerPrice(contract.origin)),maintenance=Math.round(contract.days*(1100+(100-vessel.condition)*22)),risk=routeRisk(contract.origin,contract.destination),expectedRisk=risk==='high'?18000:risk==='medium'?8000:2500,expectedNet=marketPayout-fees-fuel-maintenance-expectedRisk;const delta=Math.round((factor-1)*100),label=`Markt ${delta>=0?'+':''}${delta}% · Hafen ${(fees/1000).toFixed(0)}k · Risiko ${risk==='low'?'niedrig':risk==='medium'?'mittel':'hoch'} · erw. Netto ${Math.round(expectedNet/1000)}k`;return{marketFactor:factor,marketPayout,portFees:fees,estimatedFuel:fuel,estimatedMaintenance:maintenance,expectedNet,risk,label};}
export function bestRepositionDestination(origin:PortId,vessel:Vessel,date:string){const candidates=HUBS.filter(p=>p!==origin).map(p=>{const days=routeDays(origin,p,vessel),fuel=fuelPerDay(vessel)*days*bunkerPrice(origin),fee=PORTS[origin].fee+PORTS[p].fee;const demand=(hash(`${p}:${date.slice(0,7)}`)%31)/100;return{port:p,days,cost:Math.round(fuel+fee),score:demand*100000-(fuel+fee)};});return candidates.sort((a,b)=>b.score-a.score)[0];}
export function repositionContract(origin:PortId,vessel:Vessel,date:string):Contract{const r=bestRepositionDestination(origin,vessel,date);return{id:`R-${origin}-${r.port}-${vessel.id}`,origin,destination:r.port,cargo:`Leerpositionierung · gesch. Kosten ${Math.round(r.cost/1000)}k · neuer Markt`,cargoType:'general',tonnes:0,payout:0,days:r.days,deadlineDays:r.days+2,reposition:true};}
export function rankContracts(contracts:Contract[],vessel:Vessel,date:string){return [...contracts].sort((a,b)=>contractEconomics(b,vessel,date).expectedNet-contractEconomics(a,vessel,date).expectedNet);}
