import{describe,expect,it}from'vitest';
import{acceptContract,advanceAllVoyagesDay,availableContractsForVessel,completeHarbourArrival,createInitialState,voyageForVessel}from'./domain';
import{cargoCompatible,contractEconomics,marketFactor,repositionContract,routeDistanceNm}from'./market';

describe('VI-007 market and route economics',()=>{
 it('changes demand deterministically across market months',()=>{const s=createInitialState(),c=s.contracts.find(x=>x.id==='C-HAM-NYC-001')!;const jan=marketFactor(c,'1970-01-05'),jul=marketFactor(c,'1970-07-05');expect(jan).not.toBe(jul);expect(marketFactor(c,'1970-01-05')).toBe(jan);});
 it('applies cargo compatibility by ship class',()=>{const s=createInitialState(),container=s.contracts.find(x=>x.cargoType==='container')!,coaster=s.vessels.find(v=>v.classId==='coaster')!,feeder={...s.vessels[0],classId:'feeder' as const,className:'Feeder',capacityTonnes:14_000};expect(cargoCompatible(container,coaster)).toBe(false);expect(cargoCompatible(container,feeder)).toBe(true);});
 it('includes port fees fuel maintenance and risk in expected net',()=>{const s=createInitialState(),v=s.vessels[0],short=s.contracts.find(x=>x.id==='C-HAM-RTM-001')!,long=s.contracts.find(x=>x.id==='C-HAM-SIN-001')!,a=contractEconomics(short,v,s.campaignDate),b=contractEconomics(long,v,s.campaignDate);expect(a.portFees).toBeGreaterThan(0);expect(a.expectedNet).toBeLessThan(a.marketPayout);expect(b.risk).toBe('high');expect(b.estimatedFuel).toBeGreaterThan(a.estimatedFuel);});
 it('offers an empty repositioning choice from an idle port',()=>{const s=createInitialState(),offers=availableContractsForVessel(s,'ot-vessel-001');const r=offers.find(c=>c.reposition);expect(r).toBeDefined();expect(r?.tonnes).toBe(0);expect(r?.payout).toBe(0);expect(r?.origin).toBe('HAM');});
 it('empty repositioning costs cash and changes vessel market without completing cargo',()=>{let s={...createInitialState(),cash:1_000_000};const before=s.cash,r=repositionContract('HAM',s.vessels[0],s.campaignDate);s=acceptContract(s,'ot-vessel-001',r.id);for(let i=0;i<r.days;i++)s=advanceAllVoyagesDay(s);expect(voyageForVessel(s,'ot-vessel-001')?.arrivalPending).toBe(true);s=completeHarbourArrival(s,'ot-vessel-001',83);expect(s.cash).toBeLessThan(before);expect(s.vessels[0].currentPort).toBe(r.destination);expect(s.completedContracts).toHaveLength(0);});
 it('advances campaign date once per fleet day',()=>{let s=createInitialState();s=acceptContract(s,'ot-vessel-001','C-HAM-NYC-001');s=acceptContract(s,'ot-vessel-002','C-RTM-NYC-001');s=advanceAllVoyagesDay(s);expect(s.campaignDate).toBe('1970-01-06');});
 it('produces different preferred economics across vessel and market scenarios',()=>{const s=createInitialState(),handy=s.vessels[0],coaster=s.vessels[1],short=s.contracts.find(x=>x.id==='C-HAM-RTM-001')!,long=s.contracts.find(x=>x.id==='C-HAM-NYC-001')!;const shortCoaster=contractEconomics(short,{...coaster,currentPort:'HAM'},'1970-01-05').expectedNet,longHandy=contractEconomics(long,handy,'1970-01-05').expectedNet,shortHandy=contractEconomics(short,handy,'1970-01-05').expectedNet;expect(shortCoaster).not.toBe(shortHandy);expect(longHandy).not.toBe(shortHandy);expect(routeDistanceNm('HAM','NYC')).toBeGreaterThan(routeDistanceNm('HAM','RTM'));});
});
