import { createInitialState, type GameState, type ShipClassId, type Vessel, type Voyage } from './domain';
import { SHIP_CLASSES, createShipMarket } from './economy';

export const SAVE_KEY='ocean-trader.save.v3';
export const V2_KEY='ocean-trader.save.v2';
export const LEGACY_KEY='ocean-trader.save.v1';

type OldVessel=Omit<Vessel,'classId'|'builtYear'|'fuelCapacityTonnes'> & Partial<Pick<Vessel,'classId'|'builtYear'|'fuelCapacityTonnes'>>;
type V2State=Omit<GameState,'schemaVersion'|'vessels'|'shipMarket'> & {schemaVersion:2;vessels:OldVessel[]};
type LegacyState={schemaVersion:1;campaignDate:string;cash:number;reputation:number;vessel:OldVessel;contracts:GameState['contracts'];activeVoyage:(Omit<Voyage,'vesselId'>)|null;completedContracts:string[];transactionLog:string[]};

function classIdFor(v:OldVessel):ShipClassId{if(v.classId)return v.classId;if(v.className==='Coaster')return'coaster';if(v.className==='Feeder')return'feeder';if(v.className==='Panamax')return'panamax';return'handysize';}
function normalizeVessel(v:OldVessel,index=0):Vessel{const classId=classIdFor(v),spec=SHIP_CLASSES[classId];return{...v,classId,builtYear:v.builtYear??(1963+index),fuelCapacityTonnes:v.fuelCapacityTonnes??spec.fuelCapacityTonnes,capacityTonnes:v.capacityTonnes??spec.capacityTonnes,speedKnots:v.speedKnots??spec.speedKnots} as Vessel;}
export function serializeState(state:GameState){return JSON.stringify(state);}
export function parseState(raw:string):GameState|null{try{const value=JSON.parse(raw) as Partial<GameState>;if(value.schemaVersion!==3||typeof value.cash!=='number'||!Array.isArray(value.vessels)||!Array.isArray(value.voyages)||!Array.isArray(value.contracts)||!Array.isArray(value.shipMarket))return null;return value as GameState;}catch{return null;}}
function migrateV2(raw:string):GameState|null{try{const old=JSON.parse(raw) as Partial<V2State>;if(old.schemaVersion!==2||typeof old.cash!=='number'||!Array.isArray(old.vessels)||!Array.isArray(old.contracts)||!Array.isArray(old.voyages))return null;return{schemaVersion:3,campaignDate:old.campaignDate??'1970-01-05',cash:old.cash,reputation:old.reputation??50,vessels:old.vessels.map(normalizeVessel),contracts:old.contracts,voyages:old.voyages,shipMarket:createShipMarket(),completedContracts:old.completedContracts??[],transactionLog:['Fleet-Economy: Spielstand auf Schema v3 migriert',...(old.transactionLog??[])]};}catch{return null;}}
function migrateLegacy(raw:string):GameState|null{try{const old=JSON.parse(raw) as Partial<LegacyState>;if(old.schemaVersion!==1||!old.vessel||!Array.isArray(old.contracts)||typeof old.cash!=='number')return null;const defaults=createInitialState(),primary=normalizeVessel(old.vessel);const extraVessels=defaults.vessels.filter(v=>v.id!==primary.id);const known=new Set(old.contracts.map(c=>c.id));return{schemaVersion:3,campaignDate:old.campaignDate??'1970-01-05',cash:old.cash,reputation:old.reputation??50,vessels:[primary,...extraVessels],contracts:[...old.contracts,...defaults.contracts.filter(c=>!known.has(c.id))],voyages:old.activeVoyage?[{...old.activeVoyage,vesselId:primary.id}]:[],shipMarket:createShipMarket(),completedContracts:old.completedContracts??[],transactionLog:['Fleet-Economy: Altspielstand auf Schema v3 migriert',...(old.transactionLog??[])]};}catch{return null;}}
export function loadState(storage:Pick<Storage,'getItem'|'setItem'>):GameState|null{const current=storage.getItem(SAVE_KEY);if(current)return parseState(current);const v2=storage.getItem(V2_KEY);if(v2){const migrated=migrateV2(v2);if(migrated){storage.setItem(SAVE_KEY,serializeState(migrated));return migrated;}}const legacy=storage.getItem(LEGACY_KEY);if(!legacy)return null;const migrated=migrateLegacy(legacy);if(migrated)storage.setItem(SAVE_KEY,serializeState(migrated));return migrated;}
export function saveState(storage:Pick<Storage,'setItem'>,state:GameState){storage.setItem(SAVE_KEY,serializeState(state));}
export function clearState(storage:Pick<Storage,'removeItem'>){storage.removeItem(SAVE_KEY);storage.removeItem(V2_KEY);storage.removeItem(LEGACY_KEY);}
