import { createInitialState, seedContracts, type GameState, type ShipClassId, type Vessel, type Voyage } from './domain';
import { SHIP_CLASSES, createShipMarket } from './economy';

export const SAVE_KEY='ocean-trader.save.v6';
export const V5_KEY='ocean-trader.save.v5';
export const V4_KEY='ocean-trader.save.v4';
export const V3_KEY='ocean-trader.save.v3';
export const V2_KEY='ocean-trader.save.v2';
export const LEGACY_KEY='ocean-trader.save.v1';

type OldVessel=Omit<Vessel,'classId'|'builtYear'|'fuelCapacityTonnes'> & Partial<Pick<Vessel,'classId'|'builtYear'|'fuelCapacityTonnes'>>;
type V5State=Omit<GameState,'schemaVersion'|'eraVersion'> & {schemaVersion:5};
type V4State=Omit<V5State,'schemaVersion'|'marketVersion'> & {schemaVersion:4};
type V3State=Omit<V4State,'schemaVersion'|'loans'> & {schemaVersion:3};
type V2State=Omit<V3State,'schemaVersion'|'vessels'|'shipMarket'> & {schemaVersion:2;vessels:OldVessel[]};
type LegacyState={schemaVersion:1;campaignDate:string;cash:number;reputation:number;vessel:OldVessel;contracts:GameState['contracts'];activeVoyage:(Omit<Voyage,'vesselId'>)|null;completedContracts:string[];transactionLog:string[]};

function classIdFor(v:OldVessel):ShipClassId{if(v.classId)return v.classId;if(v.className==='Coaster')return'coaster';if(v.className==='Feeder')return'feeder';if(v.className==='Panamax')return'panamax';return'handysize';}
function normalizeVessel(v:OldVessel,index=0):Vessel{const classId=classIdFor(v),spec=SHIP_CLASSES[classId];return{...v,classId,builtYear:v.builtYear??(1963+index),fuelCapacityTonnes:v.fuelCapacityTonnes??spec.fuelCapacityTonnes,capacityTonnes:v.capacityTonnes??spec.capacityTonnes,speedKnots:v.speedKnots??spec.speedKnots} as Vessel;}
function mergeMarketContracts(existing:GameState['contracts']){const known=new Set(existing.map(c=>c.id));return[...existing,...seedContracts().filter(c=>!known.has(c.id))];}
export function serializeState(state:GameState){return JSON.stringify(state);}
export function parseState(raw:string):GameState|null{try{const value=JSON.parse(raw) as Partial<GameState>;if(value.schemaVersion!==6||value.marketVersion!==1||value.eraVersion!==1||typeof value.cash!=='number'||!Array.isArray(value.vessels)||!Array.isArray(value.voyages)||!Array.isArray(value.contracts)||!Array.isArray(value.shipMarket)||!Array.isArray(value.loans))return null;return value as GameState;}catch{return null;}}
function migrateV5(raw:string):GameState|null{try{const old=JSON.parse(raw) as Partial<V5State>;if(old.schemaVersion!==5||old.marketVersion!==1||typeof old.cash!=='number'||!Array.isArray(old.vessels)||!Array.isArray(old.contracts)||!Array.isArray(old.voyages)||!Array.isArray(old.shipMarket)||!Array.isArray(old.loans))return null;return{...old,schemaVersion:6,eraVersion:1,transactionLog:['Epochenmodell: Spielstand auf Schema v6 migriert',...(old.transactionLog??[])]} as GameState;}catch{return null;}}
function migrateV4(raw:string):GameState|null{try{const old=JSON.parse(raw) as Partial<V4State>;if(old.schemaVersion!==4||typeof old.cash!=='number'||!Array.isArray(old.vessels)||!Array.isArray(old.contracts)||!Array.isArray(old.voyages)||!Array.isArray(old.shipMarket)||!Array.isArray(old.loans))return null;return{...old,schemaVersion:6,marketVersion:1,eraVersion:1,contracts:mergeMarketContracts(old.contracts),transactionLog:['Epochen/Marktwirtschaft: Spielstand auf Schema v6 migriert',...(old.transactionLog??[])]} as GameState;}catch{return null;}}
function migrateV3(raw:string):GameState|null{try{const old=JSON.parse(raw) as Partial<V3State>;if(old.schemaVersion!==3||typeof old.cash!=='number'||!Array.isArray(old.vessels)||!Array.isArray(old.contracts)||!Array.isArray(old.voyages)||!Array.isArray(old.shipMarket))return null;return{...old,schemaVersion:6,marketVersion:1,eraVersion:1,contracts:mergeMarketContracts(old.contracts),loans:[],transactionLog:['Epochen/Markt/Finanzierung: Spielstand auf Schema v6 migriert',...(old.transactionLog??[])]} as GameState;}catch{return null;}}
function migrateV2(raw:string):GameState|null{try{const old=JSON.parse(raw) as Partial<V2State>;if(old.schemaVersion!==2||typeof old.cash!=='number'||!Array.isArray(old.vessels)||!Array.isArray(old.contracts)||!Array.isArray(old.voyages))return null;return{schemaVersion:6,marketVersion:1,eraVersion:1,campaignDate:old.campaignDate??'1970-01-05',cash:old.cash,reputation:old.reputation??50,vessels:old.vessels.map(normalizeVessel),contracts:mergeMarketContracts(old.contracts),voyages:old.voyages,shipMarket:createShipMarket(),loans:[],completedContracts:old.completedContracts??[],transactionLog:['Epochen/Fleet-Economy: Spielstand auf Schema v6 migriert',...(old.transactionLog??[])]};}catch{return null;}}
function migrateLegacy(raw:string):GameState|null{try{const old=JSON.parse(raw) as Partial<LegacyState>;if(old.schemaVersion!==1||!old.vessel||!Array.isArray(old.contracts)||typeof old.cash!=='number')return null;const defaults=createInitialState(),primary=normalizeVessel(old.vessel),extraVessels=defaults.vessels.filter(v=>v.id!==primary.id);return{schemaVersion:6,marketVersion:1,eraVersion:1,campaignDate:old.campaignDate??'1970-01-05',cash:old.cash,reputation:old.reputation??50,vessels:[primary,...extraVessels],contracts:mergeMarketContracts(old.contracts),voyages:old.activeVoyage?[{...old.activeVoyage,vesselId:primary.id}]:[],shipMarket:createShipMarket(),loans:[],completedContracts:old.completedContracts??[],transactionLog:['Epochenmodell: Altspielstand auf Schema v6 migriert',...(old.transactionLog??[])]};}catch{return null;}}
export function loadState(storage:Pick<Storage,'getItem'|'setItem'>):GameState|null{const current=storage.getItem(SAVE_KEY);if(current)return parseState(current);const v5=storage.getItem(V5_KEY);if(v5){const migrated=migrateV5(v5);if(migrated){storage.setItem(SAVE_KEY,serializeState(migrated));return migrated;}}const v4=storage.getItem(V4_KEY);if(v4){const migrated=migrateV4(v4);if(migrated){storage.setItem(SAVE_KEY,serializeState(migrated));return migrated;}}const v3=storage.getItem(V3_KEY);if(v3){const migrated=migrateV3(v3);if(migrated){storage.setItem(SAVE_KEY,serializeState(migrated));return migrated;}}const v2=storage.getItem(V2_KEY);if(v2){const migrated=migrateV2(v2);if(migrated){storage.setItem(SAVE_KEY,serializeState(migrated));return migrated;}}const legacy=storage.getItem(LEGACY_KEY);if(!legacy)return null;const migrated=migrateLegacy(legacy);if(migrated)storage.setItem(SAVE_KEY,serializeState(migrated));return migrated;}
export function saveState(storage:Pick<Storage,'setItem'>,state:GameState){storage.setItem(SAVE_KEY,serializeState(state));}
export function clearState(storage:Pick<Storage,'removeItem'>){storage.removeItem(SAVE_KEY);storage.removeItem(V5_KEY);storage.removeItem(V4_KEY);storage.removeItem(V3_KEY);storage.removeItem(V2_KEY);storage.removeItem(LEGACY_KEY);}
